=== Широкий и глубокий код

Как мы проводим рабочее время на браун филд проектах?

Обычно примерно так:
1. От кого-то приходит требование, что сейчас система ведёт себя таким образом, а надо чтобы вела себя таким образом
2. По требованиям, вы примерно понимаете обработчик сигнала, результат исполнения, которого надо изменить
3. Далее вы идёт по стэку вызовов обработчика в поисках того места, куда надо внести изменения
4. Вносите изменения
5. Отдаёте код на тестирование или в прод
6. И вам прилетает регресс

Почему так происходит?
Как обычно в этой книге - это всё из-за эффектов.
И скрытых связей
Например, в процессе изменения вы вынесли вызов какого-то метода из-под условия.
А этот метод, имел эффект, о котором вы не знали или забыли и соотвественно он стал проявляться всегда, а не только при соблюдении условия из которого вы вынесли этот метод.
Как избежать таких проблем?

Широкий код - это код который на флейм графе будет выглядеть широким.

Глубокий код - это код который на флейм графе будет выглядеть глубоким.

Туду: разжевать термины
Туду: картинки
Туду: пример с факториалом
Туду: пример с роутином?
Туду: найти ссылку на "нас учат"

Когда я был маленький, я читал книги, в которых учили писать глубокий код - код состоящий из большого количества небольших функций, вызывающих друг друга.

Однако когда я вырос, приобрёл свой опыт и посвятил размышлениям о том, как писать код свои 10 тыщ часов, я пришёл к выводу, что глубокий код не всегда хорошо.

И как обычно в этой книге, дело в эффектах.

Глубокий код вынуждает вас раскидывать эффекты по всем этим небольшим процедурам, поэтому глядя на корневую процедурам об её эффектах вы можете только догадываться по её названию.
И хорошо если название действительно отражает примерный перечень эффектов процедуры в данный момент.
А может и не отражать.

В случае же применения эргономичного подхода, с перечислением всех эффектов воркфлова в одной процедуре, глядя на эту процедуру можно понять польный перечень эффектов её вызова.

В случае же чистых функций, глубокий код вполне можно применять, т.к. в этом случае глядя на корневую функцию вы сразу по сигнатуре можете понять, что она делает.
