---
title: "Модель реляционных неизменяемых данных и моделирование информации с её помощью"
date: 2023-10-11T08:25:37+07:00
draft: false
---
:source-highlighter: rouge
:rouge-theme: github
:icons: font
:sectlinks:
:imagesdir: /microposts/23/11/images

[NOTE]
--
Этот материал является "микропостом" - текстом, написанным в режиме потока сознания без особой редактуры.

Следить за обновлениями блога можно в моём канале: https://t.me/ergonomic_code[Эргономичный код]
--

Модель реляционных неизменяемых данных является моделью предстваления информации в виде набора неизменяемых, потенциально вложенных структур данных - неотъемлемой части функционального стиля программирования.
Такая модель представляет всю БД как набор изменяемых коллекций с доступом по ключу (MutableMap<Key, Aggregate> в Kotlin), элементами которых являются неизменяемые структуры данных (data class в Kotlin).

Концептуально, модель реляционных неизменяемых данных можно проиллюстрировать следующим кодом:

[source,kotlin]
----
data class User(val id: Long, val name: String)

data class Post(val id: Long, val userId: Long, val title: String)

class Db {

    private val collections = hashMapOf<KClass<*>, MutableMap<*, *>>()

    fun createTable(type: KClass<*>) {
        collections.put(type, HashMap<*, *>())
    }

    fun upsert(aggregate: Any) {
        collections[aggregate::class][aggregate.getKey()] = aggregate
    }

    fun <T> findById(type: KClass<T>, id: Any): T? {
        return collections[type][id] as T
    }

    fun <T> findAll(type: KClass<T>): Iterable<T> {
        return collections[type].values
    }

}

val db = Db()

fun initDb() {
    db.createTable(User::class)
    db.createTable(Post::class)
    val user = User(1, "Aleksey")
    db.save(user)
    val post = Post(1, user.id, "Immutable relational data model")
    db.save(post)
}

fun addPost(userId: Long, postDto: PostDto) {
    val newPost = Post(nextPostId(), userId, postDto.title)
    db.upsert(newPost)
}

fun getPost(postId: Long): PostView {
    val post = db.findById(Post::class, postId)
    val user = db.findById(User::class, post.userId)
    return PostView(author = user.name, title = post.title)
}

fun updatePost(postId: Long, newTitle: String) {
    val post = db.findById(Post::class, postId)
    val updatedPost = post.copy(title = newTitle)
    db.upsert(updatedPost)
}

----

На практике, конечно же, данные будут храниться в каком-то хранилище постоянных данных (в этом посте - в реляционной СУБД), а в приложении база данных будет представлена в виде набора классов, реализующих шаблон Репозиторий.

== Концептуальная модель

Классической концептуальной моделью информации является Entity-Relationship модель и её можно преобразовать в модель неизменяемых реляционных данных.
Для упрощения перехода к физической модели, в качестве нотации ER-диаграммы лучше использовать нотацию https://en.wikipedia.org/wiki/Entity%E2%80%93relationship_model#Crow's_foot_notation[вороньей лапки].

[NOTE]
====
Обратите внимание, что в нотации вороньей лапки можно представить только бинарные (между двумя сущностями) отношения без атрибутов.
А отношения, связывающие три и более сущности, а так же отношения, содержащие атрибуты, должны быть преобразованы в сущности.
====

(#todo: расписать элементы ЕР-диаграммы#)

(#todo: подраздел концептуальной модели?#)
== Логическая модель

Для того чтобы концептуальная модель могла быть эффективно представлена в терминах современных языков программирования и систем хранения данных, её надо немного преобразовать.

Во-первых, надо заменить отношения Многие ко Многим (N-M) на слабые сущности, связанные отношениями Многие к Одному (N-1) с изначальными сущностями.
Здесь же, при использовании нотации, отличной от вороньей лапки, необходимо преобразовать в сущности отношения, связывающие более двух сущностей и/или имеющие атрибуты.

Во-вторых, надо ввести отношение 1 к Немногим (1-F), проанализировать имеющиеся отношения 1-N и пометить их как 1-F, в том случае, если они являются таковыми.

Отношение 1-F - это отношение, в которое естественным для предметной области образом вступает такое количество сущностей такого размера, которое можно эффективно загрузить из постоянного хранилища и передать на устройство конечного пользователя и с которым конечному пользователю будет комфортно работать как с единым целым (без средств поиска и пагинации).
Конкретное значение количества сущностей и их размер, которые можно счесть отношением 1-F, зависит от конкретной предметной области и технологии реализации
В качестве первого приближения можно взять 20 сущностей в отношении размером до 256 байт каждая.

В-третих, надо убедить, что слабые сущности вступают только в отношения 1-1 и 1-F, но не 1-N.

== Физическая модель

== Модель хранения

== Переход от концептуальной модели к логической

== Переход от логической модели к физической

== Реализация модели реляционных неизменяемых данных с помощью Spring Data JDBC
