---
title: "Я и мой целибат"
date: 2024-05-21T08:25:37+07:00
draft: false
tags: ergo-persistance spring-data-jdbc jpa functional-architecture immutable-data-model
---
:source-highlighter: rouge
:rouge-theme: github
:icons: font
:sectlinks:
:imagesdir: /drafts/ergo-persistance/images
:toc: macro
:toc-levels: 6
:toc-title: Содержание

== Я и мой целибат

В последние 4 года я отказался от многих штук, являющихся стандартом де-факто современной разработки:

. Я отказался от Лондонской школы юнит-тестирования (тестирования отдельных методов в изоляции от зависимостей) в пользу Детройтской школы - тестирования всей системы в целом через публичное API на соответствие бизнес-требованиям;
. Я отказался от императивного программирования (с изменяемыми объектами и выполнением IO в произвольных частях кода) в пользу прагматичного функционального программирования - использования неизменяемых структур данных и выполнения ввода-вывода строго в одном определённом на архитектурном уровне месте.
. Я отказался от Spring Data JPA в пользу Spring Data JDBC.

Глядя на это вы можете подумать: "О боже! Судя по тому, как он себя истязает - этот чувак убил кого-то и не покаялся!".

Но это не так.
На самом деле, эти запреты помогают мне делать проекты на 50% быстрее, допускать на 50% меньше ошибок и получать на 1000% больше кайфа от каждодневной работы.
Первые два утверждения https://azhidkov.pro/posts/23/07/project-e-results/#_%D0%B8%D1%82%D0%BE%D0%B3%D0%B8[подтверждены цифрами]^*^.

[NOTE]
====
Подтверждение, конечно, не неоспоримое, но тем не менее, я утверждаю, что в целом оно соответствует действительности.
Это подтверждается тем, что из 7 проектов, сделанных с этими ограничениями, не один не был провальным, и сделаны они для 3 заказчиков - большинство заказчиков после первого проекта приходили за вторым.
====

Про эти ограничения можно сделать три отдельных доклада и в этом я расскажу только о самом спорном - отказ от Spring Data JPA.

== Что мне не подходит в JPA?

В-первую очередь - её вшитая в спецификацию императивность.
И с учётом того, что я отказался от императивного программирования, уже это исключает для меня использование JPA.

Кроме того, благодаря таким удобным штукам, как модель связного графа изменяемых объектов, ленивой загрузке и дёрти чекингу, она ставит крест на модульности.

Наконец, это просто огромная дура, которая может вести себя таким невооразимым количеством разным способов, которые банально не влазят мне в голову.

Давайте разберём эти тезисы подробнее

== Императивность

Тут, на самом-то деле, разбирать особо не чего - она вшита в спецификацию:

(#todo: цитата#)

Поэтому эту часть я посвящу тому, что мне не подходит в императивном программировании.

=== Что не так с императивным программированием

==== Многопоточное программирование

Давайте начнём с того, что не для всех актуально, но бесспорно: императивное программирование (неизменяемые данные) в многопоточной среде - это прямая дорога в ад.

Проблема их комбинации заключается в том, что ваш поток могут в любой момент остановить и что-то поменять в данных, с которыми вы сейчас работаете.

Рассмотрим пример:

[source,java]
----
public class SharedClass {

    private final List<Integer> sharedList = new ArrayList();

    public removeFirst() {
        sharedList.remove(0)
    }

    public double avg(List<Integer> list) {
        if (list.size() == 0) {
            return 0;
        }

        long sum = sum(list);

        return ((double)sum) / list.size();
    }
}
----