---
title: "Пишем бакэнды в функциональном стиле на Kotlin и Spring Data JDBC. Почему и как."
date: 2024-05-21T08:25:37+07:00
draft: false
tags:
- ergo-persistance 
- spring-data-jdbc
- jpa 
- functional-architecture 
- immutable-domain-model
---

== Введение

Привет!

Меня зовут Алексей и с 2020 года я делаю коммерческие проекты только в функциональном стиле.

При этом важно сразу проговорить, что под функциональным стилем я понимаю то, что сам долго называл "пролетарским ФП", а сейчас оказалось что это data-oriented programming - только лишь программирование с неизменяемой моделью данных и разделение ввода-вывода и бизнес-логики.

В этом посте не будет ни одного упоминания монад, аппликативов и категорий Клейсли, не будет ни одной рекурсивной функции и не будет ни одного типа на трёхэтажных дженериках.

У вас может возникнуть резонный вопрос - "зачем идти против мейнстрима?".

Ответ на это такой: потому что могу, мне нравится и мои заказчики остаются довольными.

Аргументы против ФП:

. сложно найти людей, которые могут в ФП;

Аргументы за ФП:

. ФП ака dop - это проще (дешевле), чем ООП.

=== Проект Э

|===
|Метрика|Оригинальный проект|Отреинженеренный проект

|Стэк
|C#, OOP, микросервисы, 0 тестов, Entity Framework, Dapper
|Kotlin, DOP, модульный монолит, 100% покрытие эндпоинтов, SDJ

|Трудоёмкость
|~1512 ч/часов мидла
|1162 ч/часов юниоров

|Медианные трудозатраты на задачу
|16
|5

|Количество багов на задачу
|1,7
|0,4

|===

Чисто цифры очень хочется просуммировать так: за 80% времени мидла, юниоры сделали проект, который стало поддерживать в два раза дешевле.

Но, к сожалению, условия выполнения проектов были сильно разными, поэтому честнее будет намного более аккуратное резюме:

* SDJ и ФП не обрекут ваш проект на провал;
* ФП (при условии ревью лидом) могут писать хорошие проекты в функциональном стиле.

Это уже моё субъективное мнение, но я полагаю, что на разницу в метриках, помимо качественного тестирования и отказа от ненужных сложностей распределённого программирования, положительное влияние оказала и простата, присущая коду написанному в функциональном стиле.

Этот тезис я проиллюстрирую примером из другого коммерческого проекта.

=== Проект Баркодер

Этот пример хорош тем, что версия "до" - это реальный код, написанный юниором до ревью.
В Проекте Э таких примеров не было или они не сохранились.

Рассмотрим вот такой кусочек кода метода сервиса приложения:

[source,kotlin]
----
@Transactional
open fun repackage(boxIds: List<Long>, osgPeriods: List<OsgPeriodDto>) {
   val osgIds = osgPeriods.map { it.osgBoxId }
   if (boxIds.size == 1) {
       val box = boxRepo.findByIdOrNull(boxIds[0])
       if (osgPeriods.first().periods.isEmpty()) {
           osgPeriods.forEach {
               if (it.periods.isEmpty()) {
                   it.periods.addAll(box.reportingIntervals.map { ri ->
                       ReportingPeriodDto(
                           ri.startDate.toString(),
                           ri.endDate.toString()
                       )
                   })
               }
           }
           saveBoxWithPeriodsOnRepackage(box, osgPeriods, false)
       } else {
           saveBoxWithPeriodsOnRepackage(box, osgPeriods, true)
       }
   } else {
       boxIds.forEach { boxId ->
           val osgId = osgPeriods[0].osgBoxId
           val box = boxRepo.findByIdOrNull(boxId)
           boxRepo.save(
               box.copy(
                   reportingIntervals = box.reportingIntervals.map {
                       it.copy(
                           osgBoxId = osgId
                       )
                   }.toSet()
               )
           )
       }
       osgRepo.insertBoxesToOsgsLinks(osgIds, boxIds)
   }
}
----

Тут перемешанны бизнес-логика и ввод вывод и из-за этого понять его довольно сложно.
И я особо не надеюсь, что кто-то будет в него вникать, но тем не мнение предложу вам небольше задание по чтению императивного кода: заските время и попробуйте найти в нём проблему производительности.

Нашли?
В оригинальном коде методы findByIdOrNull и save вызываются в цикле.

Теперь давайте посмотрим, как этот же код выглядит будучи написанным функциональном стиле:

[source,kotlin]
----
val boxes = boxRepo.findByIdIn(boxIds)
val (repackedBoxes, boxOsgBoxLinks) = repackageBoxes(boxes, osgPeriods)
boxRepo.saveAll(repackedBoxes)
osgRepo.insertBoxesToOsgsLinks(boxOsgBoxLinks.boxIds, boxOsgBoxLinks.osgBoxIds)
----

Тут уже вполне можно код почитать и понять, что этот код:

. Достаёт некие коробки по идам (1 select);
. Каким-то образом их переупаковывает на основе неких периодов, в результате чего появляются изменённые коробки, а так же связи коробок с ОСГ-коробками (никакого IO);
. Сохраняет обновлённые коробки (пакетные N + K insert-ов и update-ов);
. Добавляет связи (вот тут уже без знания предметной области сложно и надо код читать).

Ну а если понять, что там за перепаковка такая, то этот код выглядит так:

[source,kotlin]
----
private fun repackageBoxes(
   boxes: List<Box>,
   osgPeriods: List<OsgPeriodDto>
): Pair<List<Box>, BoxOsgBoxLinks> = when {
   boxes.size == 1 && osgPeriods.all { it.periods.isEmpty() } -> {
       listOf(box.single().unlinkReportingIntervalsFromOsg()) to NoLinks
   }
   boxes.size == 1 && osgPeriods.all { it.periods.isNotEmpty() } -> {
       val box = boxes.single()
       val newReportingIntervals = osgPeriodsDtosToReportingIntervals(box.id!!, osgPeriods)
       listOf(box.withReportingIntervals(newReportingIntervals)) to NoLinks
   }
   else -> {
       val repackedBoxes = boxes.map { box ->
           val newReportingIntervals = osgPeriodsDtosToReportingIntervals(box.id!!, osgPeriods)
           box.withReportingIntervals(newReportingIntervals)
       }
       repackedBoxes to extractLinks(boxes, osgPeriods)
   }

private fun osgPeriodsDtosToReportingIntervals(
   boxId: Long,
   osgPeriods: List<OsgPeriodDto>
): Set<ReportingInterval> {
   val allOsgPeriods = osgPeriods.flatMap { osgBox -> osgBox.periods.map { osgBox.osgBoxId to it } }
   val newBoxReportingIntervals = allOsgPeriods.map { (osgBoxId, period) ->
       ReportingInterval(boxId, period.convertFromDateToDate(), period.convertToDateToDate(), osgBoxId)
   }
   return newBoxReportingIntervals.toSet()
}
----

Этот код вы так же вряд ли станете читать в рамках чтения поста.
Но если бы вам деваться было некуда, то вы бы были очень благодарны, что вам тут хотя бы за работой с БД следить не надо.

Вы можете сказать, что тут просто юниор на гавнокодил и в целом будете правы.
Но разделение ввода-вывода и бизнес-логики и очень простые правила как этого добиться существенно уменьшают вероятно гавнокода.

А правила такие:

. Методы сервисов не могут вызывать методы другие методы сервисов^*^;
. Методы сервисов не могут содержать циклов (а так же функций высшего порядка на коллекциях) или if-ов (за исключением защитных выражений).

^*^ - иногда это требуется, в этом случае подойди к лиду. 

=== Проект Ю

== Почему SDJ

И если вы нормальный программист и сами знакомились с этой технологией или читали посты других нормальных программистов вы можете подумать: чувак извращенец, там же гора и маленькая тележка проблем:

* Там же надо проектировать агрегаты! 
  А не понятно как это делать!
* Там же нет Many To Many!
* Там же всегда N+1!
* Там же откуда-то берутся непонятные DELETE!
* Там же нет контекста транзакции!

Все утверждения выше - истинны, SDJ действительно так и работает.

Но для меня это всё - не проблемы, а решения.

Потому что с 2012 года я предпочитаю писать код в функциональном стиле, и с 2017 года делаю это в коммерческих проектах.

И с этой колокольни особенности работы, причисленные выше, выглядят совсем по другому.

Но для того, чтобы объяснить, какие проблемы решают эти особенности работы SDJ, сначала надо рассказать, как функциональные программисты проектируют модель данных, какую модель изменения этих данных и какую архитектуру используют.

=== Разработка бакэндов глазами функционального программиста

==== Функциональная модель информации (модель модели данных)

Функциональные программисты используют, вы не поверите, самую обычную модель информации, в которой информация организована в записи - наборы пар атрибут-значение, соответствующие определённым типам.
Записи бывают двух видов - корневые и вложенные.
Корневые имеют ключевой атрибут, уникально идентифицирующие отдельную запись в наборе всех записей определённого типа.
Вложенные записи ключевых атрибутов не имеют и могут храниться только внутри одной корневой записи.

На корневую запись можно сослаться только по её ключу - добавить в ссылающуюся запись атрибут, который в качестве значения хранит ключ ссылаемой записи.

На вложенную запись сослаться нельзя, её можно только включить по значению - добавить во внешнюю запись атрибут, который в качестве значения хранит непосредственно саму запись.

Экземпляры записей организованы в коллекции - наборы пар ключ-значение, где ключами выступают ключевые атрибуты записей, а значениями - сами записи.
Соответственно в коллекции организованы только корневые записи.

Если взять классический пример с заказами, их позициями и продуктам, то:

. Заказ и продукт будут корневыми записями;
. Позиция заказа будет вложенной записью;
. Атрибут "позиции" в записи заказа - будет атрибутом включения вложенной записи;
. Атрибут "ид продукта" в записи позиции заказа будет ссылкой по ключу.
. Экземпляры записей заказ и продукт хранятся в соответствующих коллекциях.

До сих пор, функциональная модель информации мало чем отличается от объектной модели информации.
И вообще ни чем не отличается от модели информации DDD со ссылки между агрегатами через ИДы.

Отличия начинаются с того, что в функциональной модели информации записи являются не изменяемыми - значения атрибутов записи невозможно изменить, после создания экземпляра.

И тут возникает резонное возражение - заказ, это же сущность, он должен меняться!

Для того чтобы справиться с этим несовершенством реального мира, функциональные программисты-практики идут на компромисс - они допускают появление в системе изменяемых объектов, но минимизируют количество их экземпляров, и делают изменяемыми не сами записи, а их коллекции (репозитории).

И в этом случае сущность обретает для себя вполне конкретный дом - ячейку в коллекции идентифицируемой ключём этой сущности.
То есть сущность инкапсулирована внутри коллекции - вы можете запросить её текущее состояние, но изменить его вы можете только через коллекцию.

Обратите внимание на то, насколько близка эта модель к тому, как действительно работают современные БД - данные хранятся на диске организованными записи, которые ссылаются друг на друга по ключу.
И эти записи инкапсулированы внутри базы данных - вы можете запросить их текущее состояние в свой процесс, но это будет лишь копия не связанная с оригиналом и для того чтобы изменить оригинал, вам надо попрасить об этом БД.

Итого, функциональная модель информации представляет информацию в виде изменяемых коллекций неизменяемых, потенциально составных записей, идентифицируемых и ссылающихся друг на друга по ключу.
А обновление состояния сущности в систему осуществляется посредством сохранения записи с новым состоянием сущности под ключём этой сущности в соответствующей коллекции.

==== Функциональная архитектура в трёх словах

Функциональная архитектура делит код на три вида - чистое ядро (бизнес-логика), ввод-вывод (репозитории, гейтвеи и т.р.) и оркестрация (юз кейсы, интеракторы, методы сервисов приложения).

В чистое ядро входит модель предметной области в виде неизменяемых классов и бизнес-правила в виде функций без побочных эффектов (ввода-вывода и обращения к глобальному состоянию - текущему времени, например).

В ввод-вывод входит реализация интерфейсов связи с внешним миром - репозитории, клиенты внешних систем и т.д.

Оркестрация - это один метод который управляет потоком данных из ввода в чистое ядро в вывод.

В простейшем виде это выглядит так:

[source,java]
----
// Чистое ядро
public record Order(Long id, Long price) {

    public Order applyDiscount() {
        return new Order(id, (long) (price * 0.9));
    }

}

// Ввод-вывод
public interface OrdersRepo : CrudRepository<Order, Long> {}

// Орекстрация
public class DiscountsService {

    public void applyDiscount(orderId) {
        Order order = ordersRepo.findBuId(orderId)
                                .orElseThrow();
        Order discountedOrder = order.applyDiscount();
        ordersRepo.save(discountedOrder);
    }

}
----

---

И вооружившись этими знаниями можно вернуться к особенностям работы SDJ.

=== Особенности работы SDJ глазами функционального программиста

==== Там же надо проектировать агрегаты!

С моей точки зрения это не "надо проектировать агрегаты", а "наконец-то я нашёл технологию, для которой модель данных в виде деревьев неизменяемых структур данных является нативной".

До появления SDJ в мире Java было два варианта работы с БД:

* Полномасштабные ОРМы - имплементации JPA и EBeans;
* Легковесные обёртки поверх JDBC - MyBatis, JDBI, jooq, QueryDSL.

И при работе в функциональном стиле первый вариант - сразу не вариант, потому что все реализации ОРМ-ов, заслуживающие доверия, требуют изменяемой модели данных.

С вторым вариантом в целом можно жить, но все эти библиотеки, как минимум, не поддерживают из коробки каскадные модификации, которые необходимы для сохранения деревьев объектов.
И в целом каждая из библиотек второго типа требует тех или дополнительных приседаний.

А SDJ - проектируешь низеменяемую модель, развешиваешь чуть-чуть аннотаций (а если подстроиться под соглашения SDJ и обойтись без аудита - отделаться только лишь `@Id`), пишешь `repo.save(myImmutableObjectsTree)` и вуаля - оно оказалось в БД.
Ну не чудо ли?

==== Там же нет Many to *

В SDJ невозможно сделать прямую ссылку между двумя сущностями с независимыми жизненными циклами, например книги и авторы (`class Book { private Set<Author> authors; }`).
Нормальным программистам это кажется нонсенсом.

А для функционального программиста это комфортная норма жизни.

Потому что такая запись является встраиванием по текущему значению записи автора в запись книги и если оригинальная запись автора обновится внутри своей коллекции, то её копии в коллекции записей книг не обновится.

==== Там же всегда N+1!

В первую очередь надо отметить, что не N+1, а 1+K, где K - количество ассоциаций, а не количество связанных объектов.
То есть агрегат загружается обычно небольше чем за пару тройку запросов.

Но да, агрегаты в SDJ всегда загружаются целиком со всеми ассоциациями.

И для функционального программиста это прекрасно - это помогает ему обеспечить соответствие кода функциональной архитектуре и быть уверенным в том, что вызывая чистое ядро и передавая туда агрегат он может спокойно обращаться ко всем ссылкам и ходить по всем коллекциям и это не приведёт к появлению новых SQL-запросов.

А ещё это делает код самоочевидным - мне достаточно знать только лишь структуру агрегата, чтобы в 100 случаях из 100 правильно определять стоимость его загрузки.

==== Там же откуда-то берутся непонятные DELETE!

Когда вы сохраняете агрегат, все связанные с ним сущности удаляются и вставляются заново.

Соответственно, если, например, вы получаете от вэба только корень агрегата (с пустыми списками ассоциаций) и сохраняете его как есть, то при сохранении, все связанные с ним вложенные сущности будут удалены.

И это прекрасно - это именно то поведение, которе я ожидаю, потому что оно обеспечивает соблюдение такого, на мой взгляд фундаментального инварианта:

[source,java]
----
@Transactional(isolation = ISOLATION_REPEATABLE_READ)
public void repeatableRead(Aggregate agg) {
    Long id = aggRepo.save(agg);
    Aggregate read = aggRepo.findById(id);
    assert agg.equals(read);
}
----

Это опять же делает код самоочевидным - мне достаточно знать лишь фактическую структуру дерева объектов, чтобы в 100 случаях из 100 правильно определить, какие изменения будут выполнены в БД при его сохранении.

[NOTE]
====
Справедливости ради, текущая реализация сохранения агрегата - удаление всех связанных сущностей и вставка их заново, вызывает вопросы.

Я бы сделал это через безусловное удаление того, что отсутствует в списке ассоциаций, опционально обновление того, что присутствует в списке с непустым id-ом, и вставки того, что присутствует с пустым id-ом.
====

==== Там же нет контекста транзакции!

И это прекрасно!

Во-первых, функциональному программисту он не нужен - его роль выполняют локальные переменные метода оркестрации.

Во-вторых, для функционального программиста это только плюс, так как упрощает соблюдение функциональной архитектуры.

---

Итак, я делаю бакенды на SDJ, потому что эта технология лучше всего подходит для разработки в функциональном стиле.
Тут возникает следующий вопрос - почему я пишу бакэнды в функциональном стиле, а не как все белые люди в объектно-ориентированном?

На него я обязательно отвечу, но прежде чем уйти от темы проблем SDJ хочу рассказать об объекитнвых проблемах SDJ - проблемах с которыми столкнётся и объектно-ориентированный и функциональный программист.

== Объективные проблемы SDJ

=== Нет поддержки наследования

В моей практике самой болючей проблемой SDJ является отсутствие поддержки наследование.

На это есть https://github.com/spring-projects/spring-data-relational/issues/627[задача] 5-летней давности без какой-либо активности.
Поэтому на кавалерию тут надежды нет.

А у меня буквально во всех 5 проектах наследование требовалось.

Я это костылял двумя способами - рукописный репоз поверх jdbcAggregateTemplate + представление и jsonb-колонки плюс кастомный маппер.

=== Нет поддержки декларативной загрузки нескольких агрегатов

Другой довольно часто встречаемой проблемой является загрузка нескольких агрегатов.

Официальным решением этой проблемы является отдельная рид-модель - вполне допустимо завести отдельную модель с агрегатом, в который вложены другие агрегаты и отдельный репозиторий для него.

И так как чаще всего такая потребность возникает при выдаче данных для UI, это в целом работает и в трудоёмкости это не сильно уступает варианту варианту на базе Spring Data JPA - дополнительно надо только соответствующий репоз завести.

Но иногда ссылаемые агрегаты требуются для бизнес-логики и в таком случае отдельная рид-модель является ненужным дублированием на мой взгляд.

И тогда все агрегаты приходится загружать руками и кэшировать руками, что при сложной структуре связей, может быть довольно неудобно.

Для решения этой проблемы, я собрал на коленке небольшую библиотеку на 150 строк Kotlin-кода.

Она состоит из трёх частей:

. "Гидрированной" реализации AggregateReference - объекта, который содержит агрегат, и который можно поместить в поле типа AggregateReference;
. DSL описания дерева путей в модели данных по прямым ссылкам и ссылкам на агрегаты;
. Функции, которая получает на вход список агрегатов, дерево путей и jdbcAggregateTemplate и возвращает список тех же агрегатов, где можно достать данные по всем запрошенным путям.

Сторонники JPA скажут, что я изобретаю велосипед и будут правы.
Но на мой взгляд велосипед на 150 строчек кода стоит возможности писать код в функциональном стиле.

=== Слабая поддержка динамических запросов

Наконец, третьей по болючести проблемой SDJ являются динамические запросы.

Они требуются повсеместно, но на данный момент (лето 24ого, SDJ 3.3.2) для этой проблемы есть только одно официальное коробочное решение - Query By Example.

Это решение само по себе крайне ограниченное плюс совершенно не дружит с Kotlin и ненуллабельными типами.

Но для решения этой проблемы есть целый спектр воркэраундов:

. Полуофициальное Criteria API;
. Техника OR NULL;
. MyBatis;
. QueryDSL.

==== Criteria API

Большинство динамических запросов я сейчас пишу с помощью Criteria API.

Это публичное (классы, интерфейсы и методы с модификатором доступа public) API, которое не описано в Reference документации и не доступно в по умолчанию в интерфейсах репозиториев.

Но это API можно выставить с помощью пары методов-однострочников в кастомном базовом классе репозиториев:

[source,kotlin]
----
class SmartRepositoryImpl<T : Any, ID>(
    private val jdbcAggregateTemplate: JdbcAggregateOperations,
    private val entity: PersistentEntity<T, *>,
    jdbcConverter: JdbcConverter,
) : SimpleJdbcRepository<T, ID>(jdbcAggregateTemplate, entity, jdbcConverter), SmartRepository<T, ID> {

    override fun findPage(query: Query): Page<T> {
        // пагинация внутри query имеет приоритет над явно переданной пагинацией
        return jdbcAggregateTemplate.findAll(query, entity.type, Pageable.unpaged())
    }

}

@EnableJdbcRepositories(repositoryBaseClass = SmartRepositoryImpl::class, basePackages = ["pro.azhidkov.project_x"])
@Configuration
class SdjConf
----

После чего (и ещё небольшого DSL-ка на 100 строк с синтаксическим сахаром), динамические запросы пишутся и выполняются без лишних церемоний:

[source,kotlin]
----
fun findByName(pageable: Pageable, name: String?): Page<Agg> {
    val byName = (Agg::ruName isILikeIfNotNull name) OR
            (Agg:enName isILikeIfNotNull name)

    return repo.findPage(Query.query(byName).with(pageable))
}
----

Однако и у этого метода есть существенные ограничения: 

. в запросе нельзя обращаться к колонкам вложенных сущностей с отношение 1-N;
. в запросе нельзя использовать формулы и функции БД.

Поэтому иногда приходится обращаться к чистому SQL.
И в этом случае я стараюсь обойтись техникой OR NULL.

==== Техника OR NULL

Техника OR NULL проста как три копейки:

. Объявляете метод с кастомным запросом;
. Опциональные части критериев выборки сопровождаете условием `OR :param IS NULL`: `WHERE (ru_name ILIKE :ruName OR :ruName IS NULL) OR (en_name ILIKE :enName OR :enName IS NULL)`;

На этой технике можно уехать очень далеко, настолько далеко, что до MyBaits и QueryDsl у меня руки ни разу не дошли.

Но в чистом виде, у неё есть одно неприятное ограничение - она не поддерживает пагинацию.
Но и это можно обойти

===== SpEL

Если вам нужны только Slice или Window (а не Page) и/или динамическая сортировка по одной колонке, то можно обойтись поддержкой SpEL в строке запроса:

[source,kotlin]
----
@Query("SELECT * FROM table WHERE a = 0 ORDER BY :#{sortCol} OFFSET = :#{page.offset} LIMIT :#{page.pageSize}")
fun findByA(sortCol: String, pageable: Pageable)
----

Если же вам нужно получить именно Page и/или поддержать сложную то надо будет ещё пописать инфраструктурного кода.

===== NamedParameterJdbcOpertions

Для этого нам потребуется:

. В базовый класс репозов прокинуть NamedParameterJdbcOperations;
. Чуть-чуть залезть в кишочки SDJ и добыть оттуда EntityRowMapper для мапинга агрегата;
. Добавить в него метод findPage(baseQuery: String, pageable: Pageable): Page<T> на 30 строк

[source,kotlin]
----
fun findPage(baseSql: String, params: Map<String, Any>, pageable: Pageable = Pageable.unpaged(), rowMapper: RowMapper<T> = this.rowMapper): Page<T> {
        val count = namedParameterJdbcOperations.queryForObject(
        "SELECT count(*) FROM ($baseSql) data",
        params,
        Long::class.java
    )!!
    if (count == 0L) {
        val emptyPage: List<T> = emptyList()
        return PageImpl(emptyPage, pageable, count)
    }

    val dataQuery = buildString {
        appendLine("SELECT * FROM($baseSql) data")
        if (pageable.sort.isSorted) {
            append("ORDER BY ")
            appendLine(pageable.sort.map { it.property + " " + it.direction.name }.joinToString(", "))
        }
        appendLine(
            """
                    LIMIT :pageSize
                    OFFSET :offset
                    """
        )
    }
    val data = namedParameterJdbcOperations.query(
        dataQuery,
        params + mapOf("pageSize" to pageable.pageSize, "offset" to pageable.offset),
        rowMapper
    )

    return PageImpl(data, pageable, count)
}
----

---

И вот теперь мы снова можем вернуться к вопросу что же такого в ФП, ради чего я иду на все эти мучения.

== Почему ФП?

Ответ на этот такой: потому что, ФП помогает мне решать задачи в два раза быстрее и качественнее.
Чем когда я сам же решаю задачи в императивной кодовой базе.

У этого утверждения нет неопровержимых доказательств, но какие-никакие у меня есть.

=== Резюме поста

Я уже писал пост на эту тему, подробно повторять его не буду, но приведу основные тезисы:

. Константин (мужик, который ввёл в нашей индустрии понятия coupling & cohesion) говорит, что у него были эмпиритеческие свидетельства в пользу того, что программы написанные в функциональном стиле стоили дешевле;
. Делать максимум кода в функциоанльном стиле рекомендуют множество книг, включая классические Clean Code и DDD Blue Book;
. Многие эксперты, включая анкл Боба перешли на функциональный стиль и не хотят назад;
. Программы, написанные в функциональном стиле, проще поддаются автоматической оптимизации и формальной верификации, что на мой взгляд свидетельствует об их больше простоте для понимания.

В дополнение к этому посту у меня так же есть свидетельство большей эффективности работы команды с кодовой базой на основе SDJ и выполненной в функциональном стиле.

== Разработка бакендов в функциональном стиле 101

=== Алгоритм проектирования модели данных

=== Разделение ввода-вывода и бизнес-логики

== Пример

=== ТЗ

=== Проектирование модели

=== Реализация операции отображения таблицы

== Заключение

. Я пишу бакэнды в ФП стиле, потому что он позволяет мне работать эффективнее.
  Попробуйте - возможно вам тоже так будет лучше.
. ФП стиль != монадам, хвостовой рекурсии и трёхэтажным дженерикам;
. ФП стиль = неизменяемая модель и функцоинальная архитектура;
. На мой взгляд работать с БД в ФП стиле наиболее удобно с помощью SDJ.