---
title: "Почему стоит использовать Spring Data JDBC в продакшене"
date: 2024-05-21T08:25:37+07:00
draft: false
tags: 
- ergo-persistance 
- spring-data-jdbc
- jpa
---
:source-highlighter: rouge
:rouge-theme: github
:icons: font
:sectlinks:
:imagesdir: /drafts/ergo-approach/ergo-persistance/images/
:toc:
:toclevels: 4
:toc-title: Содержание


. Используйте Spring Data JDBC, а не JPA!
. Потому что простота! Простота! И простота!
. Простота самой технологии
.. Что будет при загрузке сущности в JPA? - Не известно.
... Юниор - я не знаю
... Мидл - выполнится 1 запрос
... Сеньёр - полезет смотреть аннотации на сущностях
... Техлид - полезет смотреть, что там по стеку вызовов
... Архитектор - ит депендс
.. Что будет при загрузке сущности в JDBC? - Точно известно - то-то и то-то.
. Простота чтения кода:
.. Что будет при передачи JPA-сущности в другой метод? - Не известно
... Юниор - я не знаю
... Мидл - вычислится отчёт
... Сеньёр - полезет смотреть есть ли транзакция выше по стеку
... Техлид - полезет смотреть что делает метод
... Архитектор - ит депендс
.. Что будет при передачи JDBC-сущности в другой метод? - Точно известно - ничего
. Простота определения границ модулей:
.. Можно ли считать состояние через это поле?
... Юниор - я не знаю
... Мидл - да
... Сеньёр - полезет смотреть пакеты
... Техлид - запустит ArchUnit-тесты.
... Архитектов - ит депендс
. Из этого следует, что чтение и модификация кодовой базы на базе JDBC требует меньше усилий и нервов разработчика

== Введение

JPA является де-факто стандартом работы с БД в мире Java.
Однако, я утверждаю, что это не лучшая технология для работы с БД и в качестве альтернативы предлагаю Spring Data JDBC.

Потому что простота, простота и ещё раз простота:

. Сама технология намного проще;
. Spring Data JDBC поддерживает способ моделирования данных, который упрощает понимание программ;
. Spring Data JDBC буквально принуждает разработчиков декомопзировать модель данные на небольшие и простые в понимании кусочки.

Потому, что как Канеман получил нобелевскую премию за исселдования, показывающие, что люди принимают решения по принципу "что вижу, то и есть".
А для того, чего прямо сейчас перед глазами нет - люди придумывают "логичные" истории.

То есть программисты в своей работе как правило принимают решения исходя из того, что они сию секунду видят у себя на экране плюс какая-то полувымышленная история о том, что происходит в остальной части кода.

Давайте и мы попробуем принимать решения исходя из кусочков кода "видимых прямо сейчас на экране" и абстрактной модели данных и посмотрим, что из этого выйдет.

== Демомодель данных на базе JPA

Для иллюстраций в этом посте я буду использовать следующую модель данных спроектированную по канонам JPA:

(#todo: картинка#).

Это кусочек информационной системы фитнес-тренера, она позволяет вести базы клиентов, программ и упражнений, а так же отслеживать выполнения программ клиентами.

== Сложность JPA

Имея модель данных приведённую выше, сколько запросов будет выполнено при вызове этого метода:

[source,kotlin]
----
val programsRepository = TODO()
val program: Program = programsRepository.findById(1L)
----

?

Юниор ответит: "я не знаю".

Мидл ответит: по умолчанию связи не загружаются, поэтому выполнится один запрос, который вернёт программу.

Сеньор ответит: "ща, погоди" и полезет смотреть аннотации, навешенные на сущности.

Техлид ответит: "ща, погоди" и полезет смотреть аннотации навешанные на сущности, а так же, что там по стеку вызовов выше, не было ли уже загрузок этой программы.

Архитектор ответит: - ит депендс

(#todo: мемасик#)

Сложность самой технологии JPA проявляется в том, что её поведение зависит от множества факторов, многие из которых не очевидны:

. Структуры модели;
. Аннотаций, развешанных по этой модели;
. Истории текущей сессии работы с БД.

Это, с одной стороны, позволяет очень гибко настраивать работу технологии.
Тем кто уверенно владеет технологией.

Но с другой стороны, для тех кто технологией владеет не уверенно, это позволяет выстрелить себе в ногу под любым удобным углом.

И по моей практике, тех кто не владеет технологией и создаёт множество проблем при работе с ней намного больше, чем тех, кто ей владеет.

И в целом это не удивительно - спецификация JPA занимает более 600 страниц текста мелким шрифтом.

Spring Data JDBC же является намного более простой технологией - её документация занимает порядка 150 страниц, которые включают в том числе и возможности технологии Spring Data.

И эта простота распространяется в том числе и на способы моделирования данных - в случае Spring Data JDBC воспользоваться той же моделью не получится - её придётся декомпозировать на агрегаты.

== Демомодель данных на базе Spring Data JDBC

(#todo: картинка#)

Что здесь поменялось:

. Большинство ссылок превратились в ссылки по идентификатру - связи, определяемые полями с типом AggregateReference и обозначенные прерывистыми линиями;
. Появился явный объект-значение ProgramExercise.

Эти изменения обусловлены предельно простой моделью Spring Data JDBC - агрегаты (деревья объектов доступные по прямым ссылкам) *всегда* сохраняются и загружаются целиком.

И это обеспечивает простоту поведения кода Spring Data JDBC и, как следствие, его предсказание.

== Простота SDJ

Теперь давайте ответим на тот же вопрос - сколько запросов будет выполнено - но уже в случае работы со Spring Data JDBC.

[source,kotlin]
----
val programsRepository = TODO()
val program: Program = programsRepository.findById(1L)
----

?

Ответ - два.
Первым запросом загрузится Program.
Вторым - ProgramExercises.

[NOTE]
====
Справедливости ради и тут возможен альтернативный вариант - если включена настройка (#todo: property#), то будет выполнен один запрос.
Но это единственная альтернатива и она глобальна для всего проекта.
====

== Сложность кода на базе JPA

Теперь давайте отойдём от самой технологии и рассмотрим поведение уже нашего кода.
Каковы будут эффекты выполнения этого кода:

[source,kotlin]
----
fun generateProgramDocx(program: Program) {
  val duration = calculateProgramDuration(program)
  // ...
}
----

?

Юниор ответит: "я не знаю".

Мидл ответит: "В смысле? Вычислится длительно программы".

Сеньор ответит: "ща, погоди" и полезет смотреть есть ли @Transcational выше по стеку и не взорвётся ли calculateProgramDuration c LazyInitializationException.

Техлид ответи: "ща, погоди" и полезет смотреть есть ли @Transcational выше по стеку и не взорвётся ли calculateProgramDuration c LazyInitializationException.
И, что важнее - что делает метод calculateProgramDuration - не меняет ли он состояние `program` и не будут ли потом эти изменения автоматически закоммитаны.

... Архитектор - ит депендс

Сама спецификация JPA требует, чтобы модель была изменяемая.
И это проблема - программы с изменяемым состоянием сложнее понимать - я написал об этом целый пост и не буду здесь повторять свои теоретические размышления.

Но приведу свежий пример из собственной практики.

=== Баг, наведённый изменяемым состоянием

Волею судеб, меня недавно занесло на проект с JPA.

Там была такая модель:

[source,java]
----
class Field {

    @ManyToMany
    private List<Contact> contacts;

    public void updateContacts(List<Contact> contacts) {
        getContacts().clear();
        getContacts().addAll(contacts);
    }

}
----

И такой метод обновления контактов поля:

[source,java]
----
private void updateField(Long fieldId, List<Long> contactIds) {
    List<Contact> contacts = ...
    Field field = ...
    field.updateContacts(contacts);
}
----

Потом мне потребовалось добавить сохранение в журнал аудита факта изменения поля, включая оригинальное и новое значение.

Я недолго думая добавил метод копирования поля:

[source,java]
----
    public Field copy() {
        Field copy = new Field(...);
        copy.contacts = this.contacts;
        // ...
        return copy;
    }
----

И обновил логику обновления:

[source,java]
----
private void updateField(Long fieldId, List<Long> contactIds) {
    List<Contact> contacts = ...
    Field field = ...
    Field original = field.copy()
    field.updateContacts(contacts);
    auditService.registerFieldChange(original, field, currentUser);
}
----

Видите баг?
И я его не увидел.

`field` и `original` ссылаются на один и тот же объект списка.
Соответственно, кода вызов `field.updateContacts` обновляет этот список, он изменяется и для `original` и в журнал аудита записывается одно и то же значение.

В этом примере, возможно, вы сразу увидели баг.
Но реальный код был существенно сложнее  - вызов `updateContacts` был запрятан в полиморфный вызов `consumer.accept`, у которого было порядка 10 реализаций, большая часть из которых работала с примитивами и, соответственно, не имела этой проблемы.
Благодаря неизменяемости примитивов.
Которую JPA буквально запрещает.

Вот по этому я утверждаю, что код написанный на базе JPA сложен для понимания и предсказания его поведения.

== Простота кода на базе SDJ

А что же с SDJ?

SDJ в официальной документации рекомендует делать классы модели неизменяемыми.
(#todo: линка#)
И в этом случае ответом на вопрос "Каковы будут эффекты выполнения этого кода":

[source,kotlin]
----
fun generateProgramDocx(program: Program) {
  val duration = calculateProgramDuration(program)
  // ...
}
----

?

Будет: "В смысле? Это же чистая функция - никаких эффектов кроме вычисления длительности программы не будет"^*^.

[NOTE]
====
^*^ - по крайней мере с program точно ничего не случится.
А если вы следуете функциональной - что я так же настоятельно рекомендую - то точно никаких эффектов не будет
====

== Сложность сохранения модульности в проекте на базе JPA

Я исхожу из того, что идиоматичным способом представления всех связей в модели является прямая ссылка.

Это, в свою очередь, ведёт к тому, что модель классов повторяет модель таблиц и формирует связный ((#todo: вординг#)) граф сущностей, зачастую двунаправленный.

И исходя из этого, представьте что в потоке вы пишите такой код:

[source,kotlin]
-----
val program: Program = ...
program.trainer.name = "My custom name"
-----

Вопрос - нарушит ли это модульность системы?

Юниор ответит: я не знаю.

Мидл ответит: в смысле? Ссылка же есть. Или ты о чём?

Сеньор ответит: "ща" и полезет смотреть пакеты и доки по архитектуре.

Техлид ответит: "ща" и запустит ArchUnit-тесты.

... Архитектов - ит депендс

Идиоматичный способ представления данных в JPA не подразумевает никаких границ на уровне кода.
Даже если на этапе проектирования какие-то модули на уровне документации и подразумевались,
то при реализации та лёгкость с которой по ссылкам можно эти границы нарушить (благодаря ленивой загрузке и дёрти чекингу) быстро их де-факто стирает и превращает систему в большой ком грязи.

JPA сама по себе не нарушает модульность, поэтому наверняка где-то в мире существуют модульные проекты на её базе.
Однако за 19 лет практики я таких проектов не встречал - они все были большими комьями грязи.

== Простота сохранения модульности в проекте на базе SDJ
