== Почём функциональный персистанс для народа?

анкл Боб в прошлом году написал книгу про функциональное программирование.
Так что я считаю, что можно официально заявить: хайп функционального программирования прошёл.
Теперь ФП - это вариант нормы и функциональный подход можно встретить не только в хипстерских стартапах, но и в крупных банках.

Но на бакэнде есть слон, который может легко превратить всю вашу функциональщину в тыкву - персистанс в целом и JPA в частности.

В этом докладе я расскажу выжимку своих четырёх лет опыта разработки бакэндов с неизменяемой моделью данных на базе Spring Data JDBC.
Как это можно делать без специализрованных баз данных вроде Datomic и интерпретаторов свободных монад.

== Введение

Бла-бла.

== Почему вы вообще можете захотеть ФП?


https://azhidkov.pro/posts/23/10/why-fp/[Потому что оно позволяет экономить ваши нервы и деньги бизнеса.]
[line-through]#Почти# доказано научно.

== Ну ладно, допустим я поверил, чем мне это грозит?

Придётся отказаться от циклов в ссылках между сущностями.
И ленивой загрузки.
И дёрти чекинга.
И сеттеров.
И конструктора без аргументов.
Да и вообще от объектной модели.

== Ппц. А какую тогда модель-то использовать?

Старую добрую модель структур данных.
Сейчас такие структуры данных принято называть агрегатами.
Те, что из DDD.

== Эмм. и как её проектировать?

Да в целом-то можете начать как обычно, с объектной модели.

Потом меняете отношения Many-To-Many на сущность с двумя отношениями Many-To-One.

Потом находите отношения One-To-Few (например, классические заказ и позиция).

Потом пробегаетесь по связям One-To-One и One-To-Few и смотрите на жизненный цикл связанных сущностей.
Если они могут появляться независимо друг от друга - меняете прямую ссылку на ссылку по ИДу.

Потом все отношения One-To-Many обращаете и превращаете в Many-To-One.

Потом пробегаетесь по сущностям и отмечаете "большие" сущности - у которых много полей или которые содержать blob-ы или clob-ы.

Все сущности которые остались на стороне One-To - ваши кандидаты в агрегаты.