---
title: "SOLID: Введение"
date: 2021-05-21T13:25:37+07:00
draft: true
---
:source-highlighter: rouge
:rouge-theme: github
:icons: font

Кажется, все знают, что такое SOLID.

.Если вдруг не знаете - кликните здесь
[%collapsible]
====
SOLID - это название принципов объектно-ориентированного дизайна, сформулированных Робертом Мартином, так же известного как анкл Боб.
Принципы звучат следующим образом:

. [big]##**S**##ingle Responsibility Principle: A module should have one, and only one, reason to change.
. [big]##**O**##pen/Closed Principle:: A software artifact should be open for extension but closed for modification.
. [big]##**L**##iskov Substitution Principle:: What is wanted here is something like the following substitution property: If for each object o1 of type S there is an object o2 of type T such that for all programs P defined in terms of T, the behavior of P is unchanged when o1 is substituted for o2 then S is a subtype of T
. [big]##**I**##nterface Segregation Principle:: Clients should not be forced to depend upon interfaces that they do not use.
. [big]##**D**##ependency Inversion Principle::
A. High level modules should not depend upon low level modules. both should depend upon abstractions.
+
B. Abstractions should not depend upon details. details should depend upon abstractions.
====

В университетах рассказывают принципы SOLID.
По крайней мере лично я рассказывал.
На собеседованиях спрашивают принципы SOLID.
По крайней мере я спрашиваю.
#При ревью аппелируют к принципам SOLID.#
#По крайней мере я апеллирую.#
Каждый уважающий себя блоггер от IT пишет посты о SOLID.
По крайней мере я пишу.

И при всём при этом самой распространённой архитектурой у нас всё ещё остаётся Layered http://www.laputan.org/mud/[Big Ball of Mud].

Я учился на программиста, поэтому у нас было довольно много математики, но экзамены были довольно халявные:

* Выучил определения - тройка;
* Выучил доказательства - четвёрка;
* Решил задачу - пятёрка.

И судя по моему опыту собеседования людей, у нас индустрия троешников - более-менее похожее на правду определение может дать любой кандидат с опытом более двух лет.

Привести конкретный пример, как он применил SOLID - не может уже практически никто.
В лучшем случае, говорят, что применяют Dependency Inversion Principle с помощью DI-контейнера (забегая вперёд, это неправильный ответ, DIP != Dependency Injection).

Проблема в том, что знание принципов не помогает писать хороший софт.
Применение принципов помогает писать хороший софт.

В результате мы имеем то, что имеем - очередной блоггер от ИТ (я) пишет очередную серию постов (эту) о SOLID.

(#todo: нужна какая-то подводочка#)

Не все принципы SOLID одинаково полезны:

. SRP является самым важным, но и самым сложным для понимания.
  Он имеет наибольшее значение для качества дизайна систем, но именно этот принцип нарушается чаще других;
. DIP, автоматически влекущий за собой OCP, так же имеет значительное влияние на качество дизайна.
  В отличие от SRP, DIP прост в понимании, но требует значительных дополнительных усилий в применении.
. OCP в контексте разработки прикладных программ, несёт преимущественно утилитарную функцию и только в редких случаях его стоит учитывать при дизайне всей системы;
. LSP в контексте разработки прикладных программ, имеет довольно ограниченную актуальность и практически не влияет на дизайн системы в целом;
. ISP актуален только при разработке *очень* больших систем или работе с языками с долгой компиляцией вроде C++ или Scala.
