---
title: "Диаграмма Эффектов v0.0.2: пример построения диаграммы эффектов"
description: "Этот пост ялвяется второй частью из серии постов о диаграмме эффектов и приводит пример построения диаграммы эффектов реального проекта"
date: 2022-05-02T08:25:37+07:00
draft: false
---
:source-highlighter: roug
:rouge-theme: github
:icons: font
:sectlinks:
:imagesdir: /drafts/effects-diagram/images

[NOTE]
--
Следить за обновлениями блога можно в моём канале: https://t.me/ergonomic_code[Эргономичный код]
--

Это второй пост в серии, посвящённый диаграмме эффектов:

. (#todo: линка#) Вступление - описывает необходимость в диаграмме, основные элементы диаграммы и их визуальное представление
. Пример построения, проект True Story Project (TSP) - приводит пример построения диаграммы для реального проекта
. Декомпозиция системы на модули базе диаграммы эффектов - описывает методику декомпозиции системы на модули на базе диаграммы эффектов и иллюстрирует её на примере декомпозиции проекта TSP
. Перевод диаграммы в код - описывает процесс трансляции диаграммы в исходный код на примере проекта TSP

== Диаграмма эффектов системы актуализации данных в Яндекс.Картах и 2Гис (True Story Project, TSP)

Я сейчас заканчиваю небольшой проект по автоматизации обновления информации о компании в Яндекс.Картах и 2Гис.
Это идеальный проект для иллюстрации диаграммы эффектов - он небольшой, но включает все основные типы событий и ресурсов:

image::true-story-effects.svg[link={imagesdir}/true-story-effects.svg]

Все новые коммерческие проекты я начинаю с диаграммы эффектов по целому ряду причин.

На этапе оценки диаграмма эффектов помогает определить основные блоки реализации, убедиться, что ничего не забыто и понятно как реализовать каждую из операций системы.
А формула `(<кол-во операций>+<кол-во ресурсов>) * 12 часов` даёт хорошее первое приближение трудоёмкости работы, если все операции и ресурсы типовые.

Затем я использую диаграмму эффектов для разбиения системы на модули.
Полученные модули, а так же явные и, что важнее, неявные связи между ними я использую для определения порядка выполнения работ и возможности их распараллеливания.

== Процесс построения диаграммы

Этот проект я делаю по "Time&Material", поэтому на самом деле сделал не полную диаграмму, приведённую выше, а краткую с событиями - её и будем строить в этом посте.

Итак, поехали.
На старте у меня было ТЗ, которое можно ужать до следующих пунктов:

. У заказчика есть проблема: ему необходимо держать информацию об его организациях в ряде геосервисов в актуальном состоянии
. Ключевым геосервисом являются Яндекс Карты, но дополнительно необходимо учитывать работу с 2Гис
. Организаций у заказчика существенно больше тысячи, поэтому фид необходимо обновлять по расписанию 
. Интеграция с Яндекс Картами заключается в том, что робот Яндекса приходит на специально выделенный URL и забирает оттуда фид в https://yandex.ru/support/business-priority/branches/xml-feed-sprav.html#q1__6[проприетарном XML-формате]
. Интеграция с 2Гисом выполняется посредствам отправки фида на Email, но уже в другом формате
. Яндекс требует, чтобы фид всегда был доступен по заданному URL, поэтому необходимо обеспечить постоянное хранение последнего сгенерированного фида
. Список организаций необходимо получать из специального сервиса заказчика по REST API
. Ещё часть данных хранится во внутренней СУБД заказчика и извлекается с помощью JDBC и SQL-запроса, предоставленного заказчиком
. Наконец, фид может содержать ссылки на фотографии организаций, и управление этими фотографиями должен обеспечить разрабатываемый сервис.
Доступ к этой функциональности должен быть обеспечен посредством REST API.
Конкретное хранилище изображений можно выбрать на своё усмотрение.

Работу можно начать сразу с построения диаграммы эффектов, но я обычно в первом проходе составляю просто списки событий, операций и ресурсов, т.к. по мере вычитки ТЗ их состав наверняка будет меняться и уточняться.
Кроме того, при первой вычитке ТЗ я обычно строю первую версию ER-диаграммы, но в данном случае модель данных примитивная я не буду усложнять пример её построением.

Поэтому давайте пройдёмся по "ТЗ" и сделаем на его основе три артефакта: список операций системы, список событий системы и список ресурсов.

Из пунктов №1 и 2 ясно, что потребуются интеграции с Яндексом и 2Гисом, но пока не понятно как их реализовывать.
Кроме того, из этих пунктов мы можем предположить, что нам потребуется ресурс *"Коллекция организаций"* (Organizations) - его  можно загодя добавить в список ресурсов.

[NOTE]
====
Так как все элементы диаграммы эффектов в последствии превратятся в код, а в коде имена пишутся на английском, на диаграмме я использую английский язык.
Кроме того, в среднем длина английской фразы меньше длины русского аналога, что является приятным бонусом для диаграммы.
Но чтобы не возводить лишний барьер, в посте я буду использовать русские имена, а при их первом появлении - указывать английский аналог.
====

Пункт №3 проясняет способ интеграции с Яндексом - теперь можно удалить соответствующий ресурс и заменить его на операцию *"Предоставить фид Яндекса"* (getYandexFeed) и событие *"(Получен HTTP-запрос) GET /feed/yandex"* (сейчас нет смысла тратить время на проектирование хорошего REST API - достаточно просто уникально обозначить события).
На текущем этапе кажется, что эта операция может быть обеспечена ресурсом *"Коллекция организаций"*, поэтому новых ресурсов добавлять не будем.

Пункт №4 проясняет интеграцию с 2Гис и показывает, что нам потребуется событие *"Настал момент отправки фида в 2Гис"* (пока не понятно что это за момент) и ресурс *"Email сервер"* (Email Server) - вносим их в соответствующие списки.

Пункты №5-6 помогают нам внести ряд уточнений:

. Появляется новое событие *"Истёк срок действия фида"* (FeedExpired), которое инициирует операцию *"Сгенерировать обновлённый фид"* (rebuildFeed).
. Событие *"Настал момент отправки фида в 2Гис"* на самом деле является событием *"Сгенерирован обновлённый фид"* (NewFeedGenerated) - обновляем его в списке событий
. Нам требуется где-то хранить фид для Яндекса между его генерацией и запросом - добавляем ресурс *"Фид Яндекса"* (Yandex Feed)

[NOTE]
====
В этом примере у меня случайно получился удачный порядок требований, который естественным образом привёл меня к расцепке операции генерации фида и его доставки геосервисам через событие.
Однако могло получиться и по другому.
Могло бы получиться так, что операция rebuildFeed оказалась связанной эффектами записи уже с двумя ресурсами сильно разными - YandexFeed и Email Server.

Это стало бы нарушением принципа единственности ответственности и благодаря диаграмме эффектов это нарушение сразу стало бы очевидным.

Вообще у меня есть эвристическое правило, что операция должна иметь один модифицирующий эффект и все операции с двумя и более такими эффектами я всегда подвергаю тщательному анализу.

А если бы на текущем этапе я не заметил бы ни нарушения SRP, ни собственного эвристического правила, то диаграмма эффектов привела бы меня сюда снова на этапе декомпозиции системы на модули.
Но об этом я напишу во врезке соответствующего поста.
====

Пункт №7 уточняет способ реализации ресурса *"Коллекция организаций"* - REST, уточняем его в списке.

Пункт №8 определяет ещё один ресурс операции *"Построить фид"* - *"JDBC: Дополнительная информация"* (Additional Information), добавляем его в список.

Наконец, пункт №9 определяет новый ресурс *"Фотографии"* (Photos) и набор операций *"Добавить фото организации"*, *"Получить фото организации"*, *"Получить список фото организации"*, *"Удалить фото организации"*, с набором соответствующих событий об обращениях к HTTP эндпоинтам.

В итоге у нас получились следующие списки.

События:

. HTTP: GET /feed/yandex
. Event Bus: Сгенерирован новый фид
. Scheduler: Истёк срок действия фида
. HTTP: POST /images/{org_id}
. HTTP: GET /images/{org_id}/{image_id}
. HTTP: GET /images/{org_id}
. HTTP: DELETE /images/{org_id}/{image_id}

Операции:

. Предоставить фид Яндекса
. Построить фид
. Добавить фото организации
. Получить фото
. Получить список фото организации
. Удалить фото

Ресурсы:

. REST: Коллекция организаций
. Email-сервер
. ???: Фид Яндекса
. JDBC: дополнительная информация
. ???: Фотографии

Теперь построим первую версию диаграммы эффектов, просто перенося элементы и попутно отмечая связи между ними.
Как именно переносить - сверху вниз, снизу вверх или в случайном порядке - не так важно.
Я предпочитаю идти по событиям, но для каждого события целиком раскрывать его реализацию.

Например, если начать с события *"GET /feed/yandex"*, то следом идут операция *"Предоставить фид Яндекса"* и ресурс *"Фид Яндекса"*, связанные через эффект чтения - добавляем на диаграмму.
Но откуда информация возьмётся в ресурсе?
Вследствии реакции на событие *"Сгенерирован новый фид"*, которое вызывает незамеченную ранее операцию *"Обновить фид Яндекса"* - добавляем их на диаграмму.

Операции *"Обновить фид Яндекса"* помимо ресурса *"Фид Яндекса"* потребуется и ресурс *"Библиотека работы с XML"*, но диаграмма эффектов потому и так называется, что фокусируется на ресурсах с состоянием.
Поэтому ресурсы без состояния я добавляю только в том случае, если они являются единственным ресурсом операции или в чём-то неординарны - стоят денег, непонятно какую библиотеку выбрать или с ними связаны какие-то другие риски.
И т.к. тут у нас вторичный и вполне ординарный ресурс, я его опускаю, чтобы сохранить фокус.

Далее у нас есть два пути - развернуть вторую операцию события *"Сгенерирован новый фид"* (отправку в 2Гис) или понять откуда у нас будет браться новый фид.
И так как первый путь короче - сначала быстро пройдём его, а потом вернёмся к самой сложной части - добавляем на диаграмму операцию *"Отправить фид в 2Гис"* и ресурс *"Email-Server"*.
Добавив ресурс, мы задумаемся, а не слишком ли он специфицирован?
Кажется да, поэтому Email-Server делаем стереотипом способа реализации, а саму операцию обозначаем как *"Механизм отправки фида в 2Гис"*.

Теперь возвращаемся к вопросу откуда у нас берётся новый фид.
Он генерируется операцией *"Построить фид"* в ответ на событие *"Истёк срок действия фида"* - добавляем их на диаграмму.
Но событие *"Сгенерирован новый фид"* является внутренним - мы сами должны позаботиться о его отправке.
И для этого нам нужен ресурс.
На текущем этапе кажется, что стандартного Spring Application Event Publisher будет вполне достаточно для решения этой задачи - добавим ресурс *"\<<Spring Application Event Publisher>>: Топик сгенерирован новый фид"*.

Здесь мы подходим к одному из не до конца проработанных мест в диаграмме эффектов - мне хочется отразить тот факт, что событие *"Сгенерирован новый фид"* публикуется операцией *"Сгенерировать новый фид"*, но у меня нет ощущения, что эта связь хорошо ложится на текущую концепцию диаграммы.
Тем не менее, на мой взгляд эта связь очень важна, поэтому отразим её серой стрелкой от ресурса *"Топик сгенерирован новый фид"* к событию *"Сгенерирован новый фид"*.

Для того чтобы породить событие *"Сгенерирован новый фид"*, нам нам надо этот самый новый фид сгенерировать, а для его генерации нужны ресурсы - *"Организации"*, *"Дополнительная информация"* и *"Фотографии"* - добавляем их на диаграмму.

В этот момент я могу задуматься о том, как будет реализована операция *"Сгенерировать новый фид"* - я пробегусь по списку организаций, для каждой организации подтяну дополнительную информацию и фотографии - все необходимые ресурсы есть.

Кроме того, мне надо будет проверить что внешние ресурсы предоставляют мне нужное API.
А при выборе способа реализации ресурса *"Фотографии"*, который меня пока под вопросом, мне надо будет убедиться, что выбранный способ обеспечит возможность хранения привязки файлов фотографий к организациям.
Но я это пока просто помечу в заметках по проекту и продолжу строить диаграмму эффектов.

Текущую ветку мы прошли до конца - можем вернуться к спискам, вычеркнуть то, что уже перенесли на диаграмму и обнаружить, что у нас остались только события и операции API управления фотографиями - переносим их на диаграмму и немного полируем раскаладку.

На диаграмме осталась пара вопросов - как реализовать ресурсы *"фид Яндекса"* и *"Коллекция фотографий"*.
Сами фотографии явно лучше хранить в хранилище BLOB-ов вроде Amazon S3.
Там же можно хранить и фид Яндекса - у этого ресурса тривиальное API сохранения и получения файла по ключу.

Но при ближайшем рассмотрении, выясняется, что с фотографиями есть нюанс - помимо операций по ключу есть и поиск по организации.
Теоретически это можно реализовать посредствам бакетов или "папок" S3, но на мой вкус это решение уже начинает дурно пахнуть.
А чуть позже, когда мы внимательнее изучим формат фида Яндекса, мы увидим что у фотографий есть ещё и мета информация в виде типа и тэгов - хранить в S3 это будет уже совсем плохой идеей.
Значит нам нужна более продвинутая СУБД, у меня по умолчанию - PostgreSQL.

Но хранить в PostgreSQL сотни гигабайт - тоже сомнительная затея.
Значит реализацию ресурса *"Коллекция фотографий"* будет состоять из двух частей - *"Коллекция файлов"* и *"Коллекция мета информации"*.
Модификации этих ресурсов должны быть атомарными, поэтому на диаграмме я не буду разделять ресурс, а добавлю примечание.

В итоге мы получаем финальный вариант диаграммы эффектов проекта TSP в краткой нотации (картинка кликабельна):

image::true-story-effects-short.svg[link={imagesdir}/true-story-effects-short.svg]

== Заключение

Построение диаграммы эффектов дало нам довольно много:

. В первую очередь мы чётко увидели что надо сделать - какие операции есть у системы и что они должны делать
. Мы получили список ключевых работ, которые необходимо выполнить для решения задачи - это можно взять за основу для оценки трудоёмкости работ
. Мы увидели часть реализации, в которой было легко допустить высокую сцепленность и смогли этого избежать
. Мы получили иллюстрацию, которая сформировала нам интуицию, чтобы декомпозировать систему на модули - вы же тоже видите на картинке модуль изображений, модуль фида, модули интеграции с Яндексом и 2Гисом?

Но и это ещё не всё.
Диаграмма эффектов так же даёт нам вводные для рациональной декомпозиции системы на модули и для планирования работ.
Что это за вводные я напишу в следующем посте.
