---
title: "Работа с PostgreSQL"
date: 2022-12-10T01:25:37+07:00
draft: false
---

:icons: font
:source-highlighter: rouge
:rouge-theme: github
:icons: font
:sectlinks:

[NOTE]
====
Работа над гайдлайном находится в процессе.
====

== Используйте TIMESTAMPTZ для хранения меток времени

TIMESTAMP сохраняет только полученную дату и время, игнорируя возможное наличие временной зоны, а TIMESTAMPTZ переводит полученное значение в UTC.
При извлечении TIMESTAMP возвращает сохраненное значение даты и времени без таймзоны, а TIMESTAMPTZ переводит сохраненное во временную зону подключения (таймозу серевера в случае JVM) и возвращает время в этой зоне и *саму зону*.
То есть, TIMESTAMP не делает никаких дополнительных операций над переданным значением, а TIMESTAMPTZ приводит его к UTC при сохранении и (какой-то) таймзоне и самой таймзоне при его извлечении.

== Храните время с таймзоной в двух колонках - TIMESTAMPTZ + INTERVAL/VARCHAR

Postgres не умеет хранить даты с таймзонами.
TIMESTAMP WITH TIMEZONE - это (маленькая) ложь и правильно он называется TIMESTAMP IN UTC TIMEZONE.
Если для задачи важна таймзона (создания чего-то, например, или напоминания) - её надо хранить отдельно.

Хранить таймзону можно либо либо в виде смещения в колонке INTERVAL, либо в виде строки.
Первый вариант быстрее и (в общем случае) нагляднее для человека.
Но он не учитывает политические изменения.
Например, если пользователь в таймзоне Asia/Novosibirk сохранит какую-то дату в будущем, то она запишется как +07:00.
Но если после этого, кто-то решит перевести Новосибирск на "+3 часа к Москве", то локальное представление этой даты не изменится.
Что может быть нежелательным поведением.

Хранение таймзоны строкой решает эту проблему, но работа с ней будет медленнее и большинству людей таймзона Asia/Kolkata ничего не скажет.

Если не знаете что выбрать - интервал или строку - выбирайте интервал.
