---
title: "Автоматизация тестирования"
date: 2022-12-10T01:25:37+07:00
draft: false
---

:icons: font
:source-highlighter: rouge
:rouge-theme: github
:icons: font
:sectlinks:

[NOTE]
====
Работа над гайдлайном находится в процессе.
====


== Общие принципы тестирования

Главный принцип - тесты должны проверять код, на то, что он соответствует требованиям стейкхолдеров.

Для этого тесты должны:

. Работать с системой в конфигурации максимально приближенной к боевой
. Иметь имена сформулированные в виде требования
. Взаимодействовать с системой так же, как с ней взаимодействуют клиенты - то есть через публичное АПИ.

***

== Общая структура кодовой базы тестов

Верхнеуровнево, кодовая база тестов состоит из следующих пакетов:

* assertions - классы с доменно-специфичными ассёртами
* cases - классы тестовых сценариев
* clients - классы клиентов бэка
* fixtures - классы создания экземпляров тестовых данных
* infra - вспомогательный код для запуска тестов

[source,kotlin]
----
@Test
fun `getMedicaments should contain single 'Other' entry for each insulin type`()
----

== Тесты не должны использовать продовый код напрямую

Вместо этого используйте ObjectMother для создания фикстуры и тестовое АПИ для взаимодействия с системой в обход публичного АПИ.
