
---
title: "Учимся читать SQL"
date: 2025-03-15T08:25:37+07:00
draft: false
---
:source-highlighter: rouge
:rouge-theme: github
:icons: font
:sectlinks:
:toc:
:toclevels: 4
:toc-title: Содержание
:imagesdir: /posts/25/03/images

[NOTE]
--
Следить за обновлениями блога можно в Telegram-канале: https://t.me/ergonomic_code[Эргономичный код].
--

== Введение

Я отчётливо помню, как сидел на втором курсе на лабах по БД и методом научного тыка подбирал порядок слов SQL-запросе с GROUP BY который вернёт мне нужный результат.
Потому что я не понимал как работает SQL, хотя был прилежным (на программистских курсах) студентах, ходил на лекции и делал лабы за себя и "того парня".

20 лет спустя, когда я стал  был семинаристом на лабах по БД я столкнулся с той же самой проблемой у своих студентов.
И так как за 20 лет я всё-таки понял как работает SQL я придумал для своих студентов способ объяснения, который работает очень хорошо.

И если вам пока что сложно понять что делает этот запрос:

[source,sql]
----
SELECT e.id,
       e.name,
       sum(training_budget) as sum,
       array_agg(d.name || ' - ' || de.training_budget) as details
FROM employees e
         JOIN department_employees de on e.id = de.employee_id
         JOIN departments d on de.department_id = d.id
WHERE d.location = 'Новосибирск'
GROUP BY e.id
HAVING sum(de.training_budget) > 80000
ORDER BY sum(training_budget) desc
OFFSET 1 LIMIT 1;
----

- в этом посте я дам вам инструмент, который поможет вам уверенно интерпретировать в голове SQL-запросы.

[WARNING]
====
Та модель, которая последует дальше - *это не то, как настоящие СУБД исполняют SQL-запросы*.
Это упрощённая и не полная логическая модель, с которой проще работать человеку.

Намного более подробный разбор *семантики* SELECT-а есть в посте Лукаса Эдара https://blog.jooq.org/a-beginners-guide-to-the-true-order-of-sql-operations/[https://blog.jooq.org/a-beginners-guide-to-the-true-order-of-sql-operations/], а про то как СУБД реально выполянют запросы можно почитать в книге https://postgrespro.ru/education/books/internals[PostgreSQL 17 изнутри] от ребят из Postgres Professional.
====

Но прежде чем переходить непосредственно к инструменту - рассмотрим небольшую схему БД, на которой я буду его иллюстрировать.

== Схема БД

В этом посте я буду использовать следующую схему БД:

image::data-model.drawio.svg[]

[source,sql]
----
CREATE TABLE employees
(
    id       BIGINT GENERATED ALWAYS AS IDENTITY
        PRIMARY KEY,
    passport NUMERIC(10)  NOT NULL
        UNIQUE,
    name     VARCHAR(256) NOT NULL
        CHECK (length((name)) > 3)
);

CREATE TABLE departments
(
    id       BIGINT GENERATED ALWAYS AS IDENTITY
        PRIMARY KEY,
    name     VARCHAR,
    location VARCHAR NOT NULL
);

CREATE TABLE department_employees
(
    department_id   BIGINT REFERENCES departments,
    employee_id     BIGINT REFERENCES employees,
    training_budget NUMERIC(8, 2),
    PRIMARY KEY (department_id, employee_id)
);
----

Тут у нас есть некие сотрудники и отделы, связанные отношением многие ко многим.
Кроме того, на каждого сотрудника в рамках каждого отдела выделен собственный бюджет на обучение, а сами отделы привязаны ко определённому местоположению.

Теперь можно переходить непосредственно в логической модели SELECT-запроса.

== SELECT-запрос как конвейер, по которому едут таблицы

Представьте, что SELECT-запрос - это конвейер, по которому едут таблицы, и "постами" которого являются SQL-операции, которые эти таблицы как-то трансформируют.

Но, вопреки синтаксической структуре SELECT-а, этот конвейер начинается не с операции SELECT, а с оператора FROM.

=== FROM

Оператор FROM, пожалуй является самым простым - он передаёт дальше по конвейеру всю таблицу целиком, без каких либо модификаций.

== JOIN

Следующим постом конвейера является оператор JOIN.
У JOIN-а есть несколько вариаций, основными из которых являются CROSS, INNER, LEFT, RIGHT, FULL.

Но так как это не вводный пост в SQL SELECT в целом, а пост про логическую модель его работы, я рассмотрю только необходимый мне минимум - CROSS JOIN и INNER JOIN.

[NOTE]
====
Подробное объяснение и рассмотрение JOIN-ов можно найти всё у того же Лукаса Эдара в постах https://blog.jooq.org/say-no-to-venn-diagrams-when-explaining-joins/[Say NO to Venn Diagrams When Explaining JOINs] и https://blog.jooq.org/a-probably-incomplete-comprehensive-guide-to-the-many-different-ways-to-join-tables-in-sql/[A Probably Incomplete, Comprehensive Guide to the Many Different Ways to JOIN Tables in SQL].
====

=== SELECT

[NOTE]
====
Технически, в целях оптимизации и если запрос позволяет, проекция колонок может быть "протолкнута" намного раньше в конвейере вплоть до оператора FROM.

Это можно проиллюстрировать на плане следующего запроса:

[source,sql]
----
EXPLAIN ANALYZE SELECT e.id
                FROM employees e
                         JOIN department_employees de on e.id = de.employee_id
                         JOIN departments d on de.department_id = d.id
                WHERE d.location = 'Новосибирск'
----

Исполнение этого запроса даёт следующий результат:
[source,sql]
----
Nested Loop  (cost=20.32..49.25 rows=7 width=8) (actual time=0.042..0.056 rows=8 loops=1)
  ->  Hash Join  (cost=20.18..47.87 rows=7 width=8) (actual time=0.028..0.033 rows=8 loops=1)
        Hash Cond: (de.department_id = d.id)
        ->  Seq Scan on department_employees de  (cost=0.00..24.00 rows=1400 width=16) (actual time=0.011..0.012 rows=10 loops=1)
        ->  Hash  (cost=20.12..20.12 rows=4 width=8) (actual time=0.012..0.012 rows=3 loops=1)
              Buckets: 1024  Batches: 1  Memory Usage: 9kB
              ->  Seq Scan on departments d  (cost=0.00..20.12 rows=4 width=8) (actual time=0.008..0.009 rows=3 loops=1)
                    Filter: ((location)::text = 'Новосибирск'::text)
                    Rows Removed by Filter: 2
  ->  Index Only Scan using employees_pkey on employees e  (cost=0.14..0.20 rows=1 width=8) (actual time=0.002..0.002 rows=1 loops=8)
        Index Cond: (id = de.employee_id)
        Heap Fetches: 8
Planning Time: 0.198 ms
Execution Time: 0.082 ms
----

Обратите внимание на значение `width` 10 строке: 8 байт - при выборке только id- сотрудника из всей таблицы сотрудников извлекаются только значения этой колонки.
Если же в том же самом запросе в операторе проекции добавить и колонку name, то значение `width` увеличивается до 524 байт.
====

== Приземляем логическую модель на код

== SQL-запрос, как конвейер, по которому едут строки