theme = "coder-portfolio"
defaultContentLanguage = "ru"
baseURL = "https://azhidkov.pro/"
ignoreFiles = ['-pdf.adoc$']

[params]
    langseparator = "|"

[languages]

    [[params.social]]
        name = "Telegram"
        icon = "fab fa-telegram"
        weight = 1
        url = "https://t.me/d_r_q"
    [[params.social]]
        name = "Github"
        icon = "fab fa-github"
        weight = 2
        url = "https://github.com/d-r-q/"
    [[params.social]]
        name = "Vk"
        icon = "fab fa-vk"
        weight = 3
        url = "https://vk.com/d_r_q"

    [languages.ru]
        languagecode = "ru"
        languagename = "Ru"
        languageCode = "ru-ru"
        title = "Алексей Жидков"
        [languages.ru.params]
            author = "Алексей Жидков"
            info = "Kotlin/Backend техлид"
            info1 = "Разработка и реинжиниринг ПО"
            email = "biz@azhidkov.pro"
            telegram_channel_link = "https://t.me/ergonomic_code"
            telegram_channel_name = "Эргономичный код"
            avatarurl = "images/190811-2-square-1mb.jpg"
            custom_css = ["https://use.fontawesome.com/releases/v5.2.0/css/all.css", "css/custom.css", "css/github.css", "css/JetBrains-Mono.css" ]
            description = "Разработка и реинжиниринг ПО"

            thumbnail = "images/190811-2-square-1mb.jpg"

        [[languages.ru.menu.main]]
            name = "Эргономичный подход"
            weight = 1
            url = "https://ergowiki.azhidkov.pro"

        [[languages.ru.menu.main]]
            name = "Выступления"
            weight = 2
            url ="talks"

        [[languages.ru.menu.main]]
            name = "Блог"
            weight = 3
            url ="posts"

        [[languages.ru.menu.main]]
            name = "Диаграмма эффектов"
            weight = 4
            url ="effects-diagram/landing"

        [[languages.ru.menu.main]]
            name = "Контакты"
            weight = 5
            url ="/"

[security]
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', 'asciidoctor']

[pagination]
  pagerSize = 20
