---
title: "ИП Жидков А.П. - услуги по разработке ПО"
date: 2022-04-01T08:25:37+07:00
draft: false
---
:source-highlighter: roug
:rouge-theme: github
:icons: font

== Кто я

В первую очередь я Kotlin/Backend разработчик.
Но я уже так давно в этом бизнесе, что могу сделать реализацию информационной системы под ключ.

Я занимаюсь коммерческой разработкой на платформе Java с 2005 года.
В найме вырос до руководителя проектов в https://www.excelsior.ru/[ООО "Эксельсиор"] (фактически техлид, тимлид и РП в одном лице) и руководителя команды Java в https://siberian.pro[ООО "Сибериан.ПРО"].
С 2017 года работаю как ИП и за это время сделал или поучаствовал в разработке 17 проектов для 8 заказчиков.
У меня есть успешный опыт выполнения проектов как в формате субподряда по фиксированной и почасовой стоимости, так и в формате аутстаффа.
Все мои заказчики обращались к моим услугам более одного раза.

Подробно мой опыт описан в link:++{{< ref "portfolio">}}++[портфолио].

Проживаю я в Новосибирске, но успешно работаю на удалёнке с 2018 года.

== Что я могу

Я могу сам или с привлечением дополнительных специалистов реализовать для вас информационную систему "под ключ":

. Собрать требования и составить техническое задание
. Собрать команду и организовать её работу
. Выбрать оптимальный технический стек и спроектировать на его базе эффективное и поддерживаемое решение
. Реализовать спроектированное решение
. Покрыть реализацию надёжным набором автоматических тестов
. Организовать процессы Continuous Integration и Continuous Delivery

== Чего я хочу

Я наиболее заинтересован в заказах на разработку информационных систем "под ключ" в формате подряда или субподряда.

Также готов обсудить варианты работы в формате аутстафа или штатной работы в команде, близкой мне по https://ergowiki.azhidkov.pro/[взглядам]:

. Стек - Kotlin, в крайнем случае Java 17+;
. Разработка через тесты (TDD);
. Разработка в функциональном стиле (предпочтение неизменяемым данным и разделение io и бизнес-логики);

При работе через ИП, мой час стоит 2800 рублей с налогами, в случае привлечения дополнительных специалистов стоимость их работы обговаривается отдельно.
При работе в найме мои ожидания по заработной плате - 350 т.р./месяц на руки.

== Контакты

. Telegram: https://t.me/d_r_q[d-r-q]
. Email: biz@azhidkov.pro
. Телефон: +7-923-240-49-21
. VK: https://vk.com/d_r_q
