---
title: "Обо мне"
date: 2021-03-13T13:25:37+07:00
draft: false
---

Специализируюсь на разработке информационных систем (ака серверов, бэков, АПИ) на платформе Java.
Но девятнадцать лет опыта и широкий кругозор, позволяют мне успешно реализовывать и link:++{{< ref "portfolio#_система_защиты_и_лицензирования_алгоритма_торговли_на_бирже_крипто_валют" >}}++[Десктопные приложения на Python]
и link:++{{< ref "portfolio#_ниокр_системы_захвата_видео_с_кастомной_камеры_для_компания_л">}}++[низкоуровневые системы захвата видео на C]
и link:++{{< ref "portfolio#_прототипы_android_и_ios_приложения_для_проверки_бизнес_гипотезы">}}++[мобильные приложения на Kotlin Multiplatform Mobile].
Успешность проектов я определяю по тому, что из семи заказчиков, пять обращались к моим услугам более одного раза.
Из двух оставшихся один прекратил деятельность, а второй обращался для проверки бизнес-гипотезы в сфере отличной от его основной области деятельности.

Занимаюсь коммерческим программированием с 2004 года, а с 2017 года работаю независимым консультантом.
Подробнее мой опыт описан в link:++{{< ref "portfolio">}}++[портфолио] и link:++{{< ref "resume">}}++[резюме].

Закончил ВКИ НГУ в 2006 и ФИТ НГУ 2009, в 2018 поступил в аспирантуру ИВТ СО РАН, но через год забрал документы из-за рождения ребёнка.
С 2007 года преподаю и веду дипломников в ВКИ НГУ и НГУ.

С 2020 года веду https://t.me/ergonomic_code[Телеграм-канал] и пишу link:++{{ref "posts">}}++[блог] и link:++{{< ref "book/ergo">}}++[книгу], о своём подходе к дизайну и разработке.

== Как я решаю задачи клиентов

Первым делом мы с клиентом каким-то образом начинаем общение:)
На первом звонке обсуждаем проект в общем, порядок цифр сроков и стоимости и решаем, стоит ли двигаться дальше, или сейчас разумнее разойтись.

И если принципиально мне проект интересен и по силам, а заказчика устраивает порядок цифр стоимости и сроков, то назначаем основательную встречу для обсуждения верхне-уровневых требований к проекту.

Дальше возможны варианты.
Если заказчик готов работать по "Time&Material" и его устраивает двух-трёх-кратный разброс оценки стоимости, то можно начать разработку уже на этом этапе.

Если же заказчику комфортнее работать с фиксированной стоимостью и он готов оплачивать детальное проектирование, то следующим этапом я в течении двух-пяти дней прорабатываю проект и составляю задание на первый этап разработки.
Эта работа оформляется этапом №0 и разработка официально начинается только после его оплаты.
Хотя при необходимости и достаточном уровне доверия, мы можем начать работу сразу после устного подтверждения заказчиком приёмки задания на разработку.

В не зависимости от формата работы, я делаю проект на двух-четырёх недельные этапы, каждый из которых сдаётся и оплачивается, в случае работы по фиксу.

При необходимости и договорённости с заказчиком, я привлекаю к работе *других разработчиков*, а так же специалистов по тестированию, автоматизации тестирования и девопс.
За работу привлечённых специалистов я отвечаю "как за свою собственную".

Преподавание даёт мне прямой контакт со студентами ФИТ НГУ, среди которых я лично и на основе их практической работы выбираю и привлекаю к работе самых талантливых.
Привлечение стажёров к работе сокращает как срок, так и стоимость выполнения проекта в случае работы по "T&M".
За работу (и её качество) студентов я так же отвечаю как за свои собственные.

Вне зависимости от типа проекта, разработку я веду в соответствии со своим link:++{{< ref "book/ergo">}}++[Эргономичным подходом].
Эргономичный подход, среди прочего, подразумевает покрытие тестами достаточное для организации конвейера непрерывного деплоя.
Что будет конечным пунктом конвейера - стейджинг в контуре, или продакшн - зависит от заказчика.

Так же, в обязательном порядке я предоставляю проектную и эксплуатационную документацию.

По выполнению всех работ, я даю шесть недель гарантии со дня подписания последнего акта.
Шесть недель обусловлены следующими предположениями и наблюдениями:

. заказчик провёл приёмочное тестирование перед подписанием акта;
. двух недель достаточно для вывода проекта в промышленную эксплуатацию;
. за месяц реального использования проявляются все очевидные и критические ошибки и недоработки.

Однако, на практике гарантийные случаи после сдачи последнего этапа случались лишь несколько раз.
