---
title: "Портфолио - полный список"
description: Разработка и реинжиниринг ПО
date: 2021-03-13T13:25:37+07:00
draft: false
---
:sectlinks:

=== Проект Э

link:++{{<ref "posts/23/09/project-e-part1">}}++[Проект Э] - это сервис, помогающий людям, больным диабетом, следить за своим здоровьем и делиться информацией о нём со своими близкими и лечащим врачом.
Проект разрабатывается по заказу крупного российского производителя медицинского оборудования.

В роли консультанта-техлида компании ООО «Сибериан.про» взял проект на поддержку готовым на 90%, без какой-либо сопроводительной документации и связи с изначальными разработчиками.

Я перезапустил разработку бакэнда проекта новой командой и вывел его в опытную эксплуатацию.
После двух месяцев работы стало очевидно, что ошибки, допущенные первоначальной командой (преждевременное применение микросервисной архитектуры, её некорректная реализация и экономия на автоматизации тестирования), значительно замедляют развитие проекта.
Мне удалось обосновать для заказчика необходимость реинжиниринга проекта, с помощью трёх разработчиков-юниоров я закончить его в срок и вдвое сократить среднее количество трудозатрат и ошибок в дальнейшей работе над проектом.

К текущему моменту проект находится в опытной эксплуатации, но имеет более трёх тысяч реальных пользователей, которые внесли почти миллион записей в свои дневники.

=== Система штрихкодирования для X5 Retail Group

Проект разработки информационной системы для сети супермаркетов "Пятёрочка" по автоматизации архивирования документации филиалов.
Система обеспечивает генерацию и печать уникальных штрих-кодов, с помощью которых отслеживается путь документов от магазинов в коробках из-под бананов (буквально), до хранилища https://www.osgrm.ru/[ОСГ].

В роли консультанта-техлида в компании ООО «Сибериан.про», совместно с руководителем проекта я обеспечил полный цикл создания проекта, от первоначальной оценки до сдачи проекта на поддержку заказчику.

Проект запущен в промышленную эксплуатацию и обеспечивает автоматизацию архивирования документации филиалов сети "Пятёрочка" по всей стране.

=== Система "Геосервисы" для X5 Retail Group

Проект по разработке сервиса обновления информации о филиалах Пятёрочки в Яндекс.Картах и 2Гис.

В качестве консультанта-техлида и ведущего разработчика компании ООО «БрендМейкер–ру» спроектировал и реализовал большую часть сервиса.
Проект внедрён в промышленную эксплуатацию и обеспечивает актуализацию информации о порядка 20 000 магазинов Пятёрочка по всей стране.

[#threads]
=== Реинжениринг модуля отчётности Threads для ООО «Брума Сервис»

Проект по реинжинирнгу модуля отчётности Threads (теперь https://edna.ru/chat-center/[Чат-центр edna]) - комплексного решения для организации взаимодействия с клиентами в чатах и мессенджерах.

В процессе разработки модуль накопил значительное количество тех. долга, которое привело к большому (более 20) количеству сложно исправимых ошибок и к отказам всей системы в целом из-за нехватки памяти .

В качестве внешнего консультанта я провёл обратный инжиниринг требований к модулю и спроектировал и реализовал новое техническое решение по генерации отчётов, которое решило все проблемы оригинального модуля.
Обновлённый модуль был внедрён в промышленную эксплуатацию, начал стабильно генерировать корректные отчёты и тем самым снял напряжение в отношениях с одним из ключевых клиентов моего заказчика.

=== Реинжениринг модуля маршрутизации Threads для ООО «Брума Сервис»

Проект по реинжинирингу модуля маршрутизации Threads.
Модуль маршрутизации является сердцем системы, которое соединяет клиентов и операторов, и если он не работает, вся система перестаёт функционировать.

За годы разработки этот модуль накопил большое количество техдолга, который привел к серьёзным проблемам с производительностью.
Что в свою очередь привело к критическому снижению качества обслуживания у одного из стратегических клиентов заказчика.

В качестве внешнего консультанта я провёл обратный инжиниринг требований к модулю и спроектировал и реализовал новое техническое решение реализации алгоритма маршрутизации, которое повысило пропускную способность системы в 300 раз - с 5 до 1500 чатов в секунду.
Реинжиниринг был проведён и внедрён в промышленную эксплуатацию в кратчайшие сроки (две недели до внедрения в опытную эксплуатацию и ещё две недели на отладку и внедрение нового модуля для всех клиентов) и позволил сохранить клиента для заказчика.

=== Сервер сбора и передачи данных со счётчиков электроэнергии для ООО «Завод программно-технических комплексов»

Проект по разработке сервера сбора и передачи данных со счётчиков электроэнергии.
Сервер должен был обеспечить сбор данных по гибкому расписанию со счётчиков электроэнергии различных производителей по различным каналам и протоколам связи.
Задача осложнялась тем, что каналы связи со счётчиками могли быть крайне нестабильными (GPRS-модемы, расположенные на отдалённых территориях).

В качестве ведущего разработчика я полностью спроектировал и реализовал систему - сам сервер, модуль гибкой настройки расписания сбора показаний и две реализации проприетарных протоколов коммуникации со счётчиками - и передал заказчику на внедрение.
Но компания не пережила кризис 2020 года, вызванный пандемией коронавируса, и закрыла проект.

=== Реинжиниринг графического пользовательского интерфейса портативного лидара для Teledyne Optech

Проект по устранению ошибок синхронизации в GUI-приложении заказчика на Swing Framework.
Само приложение было предназначено для управления лидаром - устройством, производимым заказчиком.
Однако приложение было написано разработчиком-стажёром и содержало больше количество ошибок синхронизации.
Из-за этого оно постоянно зависало и им было невозможно пользоваться.

В качестве консультанта я разработал специализированный инструмент на базе низкоуровневого Java Debug Interface, выявил и устранил все проблемные места и передал исправленную версию заказчику для дальнейшего внедрения в промышленную эксплуатацию.

=== Поддержка Тomcat 8.5 и 9 в Excelsior JET для ООО «Эксельсиор»

Проект по поддержке очередных версий сервера приложений Tomcat в сертифицированной виртуальной машине Java с Ahead-of-Time компиляцией Excelsior JET.

В качестве консультанта я проанализировал изменения в коде загрузки классов веб-приложений Tomcat-а и портировал их в статический анализатор war-приложений компилятора, а так же в загрузчик классов в среде выполнения (Runtime) виртуальной машины Excelsior JET.

Проект внедрён в промышленную эксплуатацию в рамках Excelsior JET 15.3.

[#lpx]
=== НИОКР системы захвата видео с кастомной камеры для ООО «Сибирский центр транспортных технологий»

Проект по разработке прототипа системы захвата видео с камеры по сигналу от устройства выявления приближения железнодорожного состава.
И камера, и устройство разработаны инженерами заказчика.

В качестве ведущего разработчика адаптировал существующий open source-драйвер сенсора камеры, реализовал драйвер USB-устройства заказчика для Linux и создал управляющую программу, которая по командам устройства сохраняла изображения с камеры и предоставляла HTTP API для их получения.

Прототип был передан заказчику, после чего был доработан его инженерами и внедрён в промышленную эксплуатацию.

=== Динамически настраиваемый проксирующий middleware для ООО «Обоз»

Проект по разработке проксирующего middleware с динамической конфигурацией, получаемой из Consul.

В роли консультанта компании ООО «Сибериан.про» выполнил всю разработку проекта от первичной оценки до передачи заказчику для внедрения.

[#lobby]
=== Middleware приложения для проверки бизнес-гипотезы новой механики онлайн лотереи

Проект по разработке middleware-расширения основной системы заказчика (онлайн лотереи) для проверки бизнес-гипотезы новой игровой механики.
Большую часть данных и игровую механику предоставляла основная система заказчика, а разработанный проект обеспечивал реализацию механизма "распаковки" - симуляцию розыгрыша для игрока в удобный для него момент.

В качестве ведущего бакэнд-разработчика полностью оценил, спроектировал и реализовал весь бакэнд проекта за фиксированную стоимость.

Проект был запущен в опытную эксплуатацию, однако гипотеза не подтвердилась и заказчик закрыл проект.

[#yts_bot]
=== Система защиты и лицензирования алгоритма торговли на бирже криптовалют для ООО «Трейдинг Клуб»

Проект по лицензированию алгоритма торговли на бирже криптовалют.
У заказчика был реализован на Python алгоритм торговли на бирже криптовалют, который он планировал продавать своим клиентам.
Для защиты ноу-хау заказчика необходимо было исключить возможность реверс-инжиниринга алгоритма и его несанкционированное использование.
Кроме того алгоритм был реализован в виде консольного приложения, которое было неудобно в использовании для клиентов заказчика. Поэтому дополнительно надо было реализовать графический пользовательский интерфейс для настройки алгоритма и управления его работой.

В качестве техлида для решения этих задач я:

. Собрал и описал требования к решению;
. Реализовал сервер лицензий;
. Внедрил проверку лицензии в код алгоритма торговли;
. Реализовал сборку алгоритма в нативный код с помощью Cython;
. Реализовал настольное приложение для управления программой торговли.

Проект был сделан за фиксированную цену и сдан и внедрён в промышленную эксплуатацию в срок.

[#tcs]
=== Бакэнд системы автоматической торговли на бирже криптовалют для ООО «Трейдинг Клуб»

Проект по разработке бакэнда для мобильного приложения мониторинга алгоритма торговли на бирже криптовалют.
Бакэнд должен был предоставлять для мобильного приложения заказчика информацию о текущих результатах торговли и пуш-нотификации о важных событиях в работе алгоритма.

В роли техлида с помощью двух юниор-разработчиков полностью обеспечил реализацию проекта за фиксированную стоимость - выполнил оценку, собрал и описал требования, спроектировал архитектуру системы, организовал работу команды и реализовал часть функциональности.

Проект был выполнен в срок и успешно прошёл приёмочные испытания, однако по неизвестным мне причинам, заказчик не стал внедрять его в промышленную эксплуатацию.

[#udobno]
=== Прототипы Android и iOS приложений для проверки бизнес-гипотезы для ООО «Геймон Продакшн»

Проект по разработке прототипов мобильных приложений для Android и iOS на Kotlin Multiplatform Mobile.
Приложения позволяли пользователям автоматизировать подачу заявок на кредитные карты в различных банках, а так же заявки на открытие ООО и ИП в налоговую.

В роли техлида двух юниор-разработчиков и ведущего разработчика полностью обеспечил реализацию проекта - выполнил оценку, спроектировал архитектуру, организовал работу команды и реализовал самую сложную часть системы.

В рамках работ был реализован объём функциональности достаточный для проверки гипотезы, однако она не подтвердилась и заказчик прекратил разработку.

=== Миграция пользовательских файлов Jeffit для ООО «Брума Сервис»

Проект по миграции 2,5 миллионов пользовательских файлов общим объёмом в 40 гигабайт из https://jackrabbit.apache.org/jcr/index.html[Apache Jackrabbit] в https://min.io/[Minio] без простоя для https://jeffit.ru/[Jeffit] - информационной системы юридических фирм и департаментов.

В рамках решения задачи были выполнены работы:

. Интеграция основной системы с Minio;
. Доработка существующего модуля хранения файлов для одновременной работы с Jackrabbit и Minio на период миграции данных;
. Утилита миграции данных с возможностью продолжения работы после сбоя.

В роли техлида и ведущего разработчика обеспечил реализацию проекта за фиксированную стоимость - выполнил оценку, спроектировал решение, организовал работу юниор-разработчика и сам выполнил часть работ.

С помощью утилиты была успешно проведена миграция данных, а код интеграции с Minio внедрён в промышленную эксплуатацию.

=== Специализированная геоинформационная система для ООО «НГ-Транс»

https://play.google.com/store/apps/details?id=ru.ngtrans.camp[Кэмп] - MVP специализированной геоинформационной системы для водителей-дальнобойщиков.
В отличие от геоинформационных систем общего назначения Кэмп позволяет найти не просто гостиницу по пути следования, а место, где водитель может и сам переночевать, и рефрижератор на 86 "кубов" припарковать.

В роли техлида-консультанта компании ООО «Сибериан.про» обеспечил реализацию бакэнда системы - выполнил оценку проекта, спроектировал архитектуру и организовал работу двух юниор-разработчиков.

Весь проект был сделан в срок и в рамках бюджета, однако заказчик не стал продолжать его развитие.

=== Адаптер API хранения файлов Brandmaker для ООО «БрендМейкер–ру»

Проект по реализации адаптера API хранилища файлов https://www.brandmaker.com/de/[BrandMaker].
В рамках миграции системы на новое хранилище файлов, заказчику потребовался временный адаптер API, который бы позволил системе начать работать с новым хранилищем до её перевода на новое АПИ.

В роли ведущего разработчика полностью реализовал проект сам.

Проект был внедрён в промышленную эксплуатацию, позволил заказчику быстро решить критические проблемы с производительностью и дал время команде разработки основной системы для перехода на новое АПИ.