---
title: "Портфолио"
description: Разработка и реинжиниринг ПО
date: 2021-03-13T13:25:37+07:00
draft: false
---
:!table-caption:
:sectlinks:

== Жидков Алексей Павлович

{empty} +

Занимаюсь коммерческой разработкой ПО с 2005 года (в основном бакэндами на платформе Java).
За это время побывал практически во всех ролях, связанных с созданием ПО - разработчика, бизнес- и системного аналитика, архитектора, тех- и тим-лида, руководителя проектов и функциональной команды.

С 2017 года работаю независимым консультантом и сделал сам или организовал разработку 17 проектов для 8 заказчиков, большинство из которых прибегали к моим услугам более одного раза.

Систематизировал свой опыт в "link:++{{< ref "ergo-approach/landing">}}++[Эргономичный подход]" - гайдлайн разработки, который обеспечивает link:++{{< ref "posts/23/07/project-e-results/">}}++[высокую скорость и качество работы], даже при реализации проекта силами молодых разработчиков.

=== Портфолио

==== Проект Э

link:++{{<ref "posts/23/09/project-e-part1">}}++[Проект Э] - это сервис, помогающий людям, больным диабетом, следить за своим здоровьем и делиться информацией о нём со своими близкими и лечащим врачом.
Проект разрабатывается по заказу крупного российского производителя медицинского оборудования.

В роли консультанта-техлида компании ООО «Сибериан.про» взял проект на поддержку готовым на 90%, без какой-либо сопроводительной документации и связи с изначальными разработчиками, перезапустил разработку бакэнда проекта новой командой и вывел его в опытную эксплуатацию.

После двух месяцев работы стало очевидно, что ошибки, допущенные первоначальной командой (преждевременное применение микросервисной архитектуры, её некорректная реализация и экономия на автоматизации тестирования), значительно замедляют развитие проекта.
Мне удалось обосновать для заказчика необходимость реинжиниринга проекта, выполнить его в срок силами трёх разработчиков-юниоров и вдвое сократить среднее количество трудозатрат и ошибок в дальнейшей работе над проектом.

К текущему моменту проект находится в опытной эксплуатации, но имеет более трёх тысяч реальных пользователей, которые внесли почти миллион записей в свои дневники.

==== Система штрихкодирования для X5 Group

Проект по разработке информационной системы для сети супермаркетов "Пятёрочка" по автоматизации процесса архивирования документации филиалов.
Система обеспечивает генерацию и печать уникальных штрихкодов, с помощью которых отслеживается путь документов от магазинов в коробках из-под бананов (буквально) до хранилища https://www.osgrm.ru/[ОСГ].

В роли консультанта-техлида в компании ООО «Сибериан.про», совместно с руководителем проекта я обеспечил полный цикл разработки от первоначальной оценки до сдачи проекта на поддержку заказчику.

Проект запущен в промышленную эксплуатацию и обеспечивает автоматизацию архивирования документации филиалов сети "Пятёрочка" по всей стране.

==== Система "Геосервисы" для X5 Group

Проект по разработке сервиса обновления информации о филиалах Пятёрочки в Яндекс.Картах и 2Гис.
Сервис собирает информацию о филиалах из нескольких внутренних источников, агрегирует её и приводит к форматам, которые удовлетворяют требованиям Яндекс.Карт и 2Гис-а.

В качестве консультанта компании ООО «БрендМейкер–ру» и в роли техлида и ведущего разработчика спроектировал и реализовал большую часть сервиса.

Проект внедрён в промышленную эксплуатацию и обеспечивает актуализацию информации в Яндекс.Картах и 2Гис о 20 000 магазинов Пятёрочка по всей стране.

[#threads]
==== Реинжениринг модуля отчётности Threads для ООО «Брума Сервис»

Проект по реинжинирингу модуля отчётности Threads (теперь https://edna.ru/chat-center/[Чат-центр edna]) - комплексного решения для организации взаимодействия с клиентами в чатах и мессенджерах.

В процессе разработки модуль накопил значительное количество тех. долга, которое привело к большому (более 20) количеству сложно исправимых ошибок и к отказам всей системы в целом из-за чрезмерного потребления памяти модулем.

В качестве внешнего консультанта я провёл обратный инжиниринг требований к модулю и спроектировал и реализовал новое техническое решение по генерации отчётов, которое устранило все проблемы оригинального модуля.
Обновлённый модуль был внедрён в промышленную эксплуатацию, начал стабильно генерировать корректные отчёты и тем самым снял напряжение в отношениях с одним из ключевых клиентов моего заказчика.

==== Реинжениринг модуля маршрутизации Threads для ООО «Брума Сервис»

Проект по реинжинирингу модуля маршрутизации Threads, который является сердцем системы и соединяет клиентов и операторов.
Этот модуль имеет критически важное значение для работы системы и если он не работает - вся система перестаёт функционировать.

За годы разработки этот модуль накопил большое количество тех. долга, который привёл к серьёзным проблемам с производительностью.
Что, в свою очередь, привело к существенному снижению качества обслуживания у одного из стратегических клиентов заказчика.

В качестве внешнего консультанта я провёл обратный инжиниринг требований к модулю и спроектировал и реализовал новое техническое решение реализации алгоритма маршрутизации, которое повысило пропускную способность системы в 300 раз - с 5 до 1500 чатов в секунду.
реинжиниринг был проведён и внедрён в промышленную эксплуатацию в кратчайшие сроки (две недели до внедрения в опытную эксплуатацию и ещё две недели на отладку и внедрение нового модуля для всех клиентов) и помог сохранить заказчику важного клиента.

---

link:++{{< ref "portfolio-full-list" >}}++[Полный список проектов].
