---
date: 2021-03-13T13:25:37+07:00
draft: false
---

== Жидков Алексей Павлович
*Архитектор, техлид* +
https://azhidkov.pro +

{empty} +

=== Образование

* Аспирант ИВТ СО РАН, 2018-2019, занимался исследованиями в области разрешения конфликтов асинхронной репликации данных на основе прототипа встраиваемой многоверсионной СУБД собственной разработки.
  Временно забрал документы в связи с рождением ребёнка;
* Отделение прикладной информатики ФИТ НГУ, выпуск 2009 года;
* ВКИ НГУ, выпуск 2006 года.

{empty} +

=== Ключевые навыки

* link:++{{< ref "book/developing-ergonomic-code">}}++[Авторский подход] к разработке быстрого, надёжного и поддерживаемого ПО;
* Знаю ООП, ФП, ПП, ООД и ФД достаточно, чтобы понимать что:
** Парадигма языка программирования проекта, ортогональна парадигме разработки проекта.
+
И сейчас самая распространённая парадигама разработки - процедурное программирование;
** ООП и ФП - это синтаксический сахар;
** ООД и ФД - не взаимоисключают друг друга, а наоборот только вместе дают хороший дизайн.
* Языки программирования:
** Kotlin, Java - профессионально, с 2012 и 2002 года соотвественно;
** JavaScript, Python, C - есть успешный коммерческий опыт;
** Rust, Clojure, Scala, OCaml, Groovy, Eiffel - изучил из любопытства, но не применял.
* Реляционная модель и SQL. Из СУБД предпочитаю PostgreSQL;
* Git, Gradle;
* Spring Boot + Web MVC/Flux, Ktor;
* Spring Data JDBC/R2DBC, jooq, Ebean (могу, но не люблю JPA/Hibernate, Spring Data JPA);
* Автоматизация тестирования — xUnit, testcontainers, property testing, mutational testing.

{empty} +

=== Опыт работы

*Место работы:* ИП Жидков А. П. +
*Время работы:* Июль 2017 - текущий момент  +
См. link:++{{< ref "portfolio">}}++[портфолио].

{empty} +

*Место работы:* НГУ, Преподаватель, научный руководитель дипломных работ +
*Время работы:* Сентябрь 2009 – текущий момент +

* Семинарист курса "Базы Данных" (2018-настоящий момент);
* Лектор и семинарист курса "Объектно-Ориентированное программирование" (2009-2014).

{empty} +

*Место работы:* Excelsior, инженер, руководитель проектов +
*Время работы:* Июнь 2013 - июнь 2017  +

* https://www.teledyneoptech.com/en/products/software/lms/[Lidar Mapping Suite] - система для обработки данных полученных лидарами;
* SendItBetter (более не доступен) - сервис отправки больших файлов по e-mail;
* https://github.com/excelsior-oss/restler[Restler] - библиотека генерации клиентов HTTP-API по описанию Java-классом;
* ExcelsiorJet (более не доступен) - сертифицированная реализация JVM и AOT-компилятор Java.

{empty} +

*Место работы:* Playtox, инженер +
*Время работы:* Сентябрь 2012 – май 2013  +
Разработка платформы для мобильных MMO игр.

{empty} +

*Место работы:* КА Алексея Сухорукова, эксперт по Java +
*Время работы:* Июнь 2010 – август 2013 +
Оценка уровня владения Java соискателями.

{empty} +

*Место работы:* Алавар.ру, HD Soft (с ноября 2009), инженер +
*Время работы:* Октябрь 2008 – сентябрь 2012 +
Разработка Java-платформы для приставок кабельных сетей цифрового телевидения США и прикладных приложений для них же.

{empty} +

*Место работы:* Инновационные технологии, инженер +
*Время работы:* Март 2008 – октябрь 2008 +
Разработка городского информационного портала «Город-гид».

{empty} +

*Место работы:* ВКИ НГУ, Преподаватель, научный руководитель дипломных работ +
*Время работы:* Февраль 2007 – июль 2016 +
Лектор и семинарист базового проекта "Трансляторы".

{empty} +

*Место работы:* КБ  Информ, инженер +
*Время работы:* Январь 2006 – март 2008 +
Разработка автоматизированной информационно-измерительной системы коммерческого учёта электроэнергии.

{empty} +

*Место работы:* ТрендСВ, младший инженер +
*Время работы:* Май 2005 – октябрь 2005 +
SaaS для риелторов США.

{empty} +
