---
title: "Услуги"
date: 2021-02-23T13:25:37+07:00
draft: false
---
Я специализируюсь на разработке информационных систем на платформе Java.
Но благодаря широкому кругозору и почти двадцати годам опыта, я успешно решаю задачи в различных областях - от системы защиты интеллектуальной собственности, до драйвера для кастомной камеры.

Мой +++<a href="{{< ref "book/developing-ergonomic-code" >}}">Эргономичный подход</a>+++  к разработке, помогает мне создавать системы существенно более качественные, чем в среднем по рынку.
Это подтверждают мои клиенты, которые всегда обращаются к моим услугам повторно.

== Разработка ПО

. Автоматизирую или выведу в онлайн ваш бизнес с минимальной стоимостью в долгосрочной перспективе;
. Разработаю прототип для проверки бизнес-гипотезы минимальные сроки и бюджет.

== Аудит ПО

Помогу локализовать и решить проблемы с производительностью ПО или команды разработки.

В одном из проектов, применение принципов Эргономичного подхода позволило увеличить производительность одного из ключевых компонентов системы в 300 (триста) раз.

== Обучение

Проведу обучение вашей команды принципам Эргономичного подхода.
