---
title: "Услуги"
date: 2021-02-23T13:25:37+07:00
draft: false
---
Специализируюсь на создании информационных систем на платформе Java.
Но благодаря девятнадцати годам опыта в двадцати российских и американских проектах, решаю в срок и бюджет задачи и в других областях - начиная с комплексного решения защиты интеллектуальной собственности, и заканчивая драйвером для кастомной камеры.

Авторский +++<a href="{{< ref "book/developing-ergonomic-code" >}}">Эргономичный подход</a>+++ к дизайну и программированию, помогает создавать действительно гибкие и надёжные решения.
Это подтверждают клиенты, которые всегда обращаются к моим услугам повторно.

== Разработка ПО

. Автоматизирую или выведу в онлайн бизнес с минимальной стоимостью в долгосрочной перспективе;
. Разработаю прототип для проверки бизнес-гипотезы минимальные сроки и бюджет.

== Аудит ПО

Помогу локализовать и решить проблемы с производительностью ПО, скоростью выпуска новых фич и количеством багов.

Например, применение принципов Эргономичного подхода позволило уменьшить время отклика под нагрузкой с пяти минут до одной секунды.

== Тренинги

Проведу тренинг о принципах Эргономичного подхода. [logo]#image:/images/logo.svg[]#
