---
title: "Диаграмма Эффектов"
date: 2022-07-22T01:25:37+07:00
draft: false
---

:source-highlighter: rouge
:rouge-theme: github
:icons: font
:sectlinks:
:imagesdir: /effects-diagram/images/landing

Диаграмма Эффектов - это инструмент разработчика, созданный для визуализации поведения информационной системы через её эффекты.
Эффекты - это взаимодействие системы с внешним миром (например, запись и чтение диска, обращение к БД, обращение к внешним сервисам и т.п.).

Такое представление полезно на всех этапах разработки ПО - от первичного анализа до планирования работ и поддержки.

(#todo: маркетинговый булшит#)

*На этапе первичного анализа - снижение затрат*.
Диаграмма Эффектов помогает проектировщику быстрее построить целостную картину реализации будущей системы.

*На этапе проектирования - упрощение процесса декомпозиции*.
Диаграмма Эффектов помогает наглядно проявить как необходимую сцепленность, которая образует ядра подсистем (микросервисов, если угодно), так и случайную сцепленность, которую следует исключить.
Благодаря этому декомпозиция на подсистемы становится тривиальной задачей, выполнимой по простой методике.

*На этапе планирования работ - снижение затрат*.
Диаграмма Эффектов наглядно демонстрирует зависимости между подсистемами, что позволяет быстро определить порядок выполнения работ и найти возможности их распараллеливания.
Это позволяет команде построить более эффективный процесс разработки и уменьшить календарные сроки выполнения задач.

*На этапе поддержки - снижение количества регрессий*.
Диаграмма Эффектов помогает проанализировать текущее поведение системы, понять, как оно должно и *не* должно измениться, и проявить скрытые связи в системе.
Результатом этого является снижение количества регрессий.

== Нотации

В зависимости от ваших целей, вы можете выбрать одну из трёх нотаций Диаграммы Эффектов:

(#todo: переделать нотации в спеке#)

. Облегчённая - содержит только эффекты.
  Используется для экспресс-анализа и проектирования.
. Краткая - дополнительно содержит события, на которые реагирует система.
  Используется в случае, когда система реагирует на события, доставляемые посредством множества различных протоколов и интерфейсов (REST, SOAP, очереди сообщений, планировщики задач).
. Полная - дополнительно включает внешние элементы системы, а так же краткие описания всех составных частей.
  Используется для анализа и оценки проектов с фиксированной стоимостью и документирования реализации.

== Кейсы

=== True Story Project

(#todo: ревью#)
True Story Project - это первая информационня система, спроектированная с помощью Диаграммы Эффектов текущей версии.
Это система для обновления информации о филиалах одного из крупнейших ритейлеров России в Яндекс картах и 2Гис.
Система обеспечивает хранение фотографий филиалов, сбор информации о них из нескольких внутренних источников и обновление информации в геосервисах по расписанию.

Применение Диаграммы Эффектов для проектирования TSP помогло предотвратить ошибку проектирования, которая бы снизила надёжность системы и повысила стоимость дальнейшего развития.
Подробнее о процессе построения Диаграммы Эффектов TSP можно прочитать в этом link:++{{< ref "posts/22/06/220611-true-story-project">}}++[посте].

Этот проект был выполнен на условиях почасовой оплаты, поэтому для него использовалась краткая нотация Диаграммы Эффектов (картинка кликабельна):

image::true-story-effects-short.svg[link={imagesdir}/true-story-effects-short.svg]

=== Кэмп

https://play.google.com/store/apps/details?id=ru.ngtrans.camp[Кэмп] - MVP специализированной геоинформационной системы для водителей-дальнобойщиков.
В отличие от больших геоинформационных систем общего назначения, Кэмп позволяет найти не просто гостиницу по пути следования, а место где можно и самому переночевать и рефрижиратор на 86 "кубов" пристроить.

С точки зрения разработки этот проект интересен тем, что его целиком делали молодые специалисты, а ведущие разработчики только консультировали и проводили ревью артефакторв.
Лидом бакэнда был я и со своими джунами мы начали работу с построения Диаграммы Эффектов.
Создание Диаграммы Эффектов и декомпозиция на её базе позволила даже начинающим разработчикам разбить систему на понятные и низкосцепленные модули.
Через пару месяцев от начала проекта я практически полностью от него отключился, а в конце проекта получил такую обратную связь от РП: "К бэку у меня вообще претензий нет. Он просто работает".

image::camp-effects.drawio.svg[link={imagesdir}/camp-effects.drawio.svg]

== Спецификация

В формате link:++{{< ref "effects-diagram/specification-html">}}++[HTML] и link:../specification.pdf[PDF] .

== Шаблон Draw.io

++++
<a href="../effects-diagram.drawio" download>Шаблон Draw.io-файла</a> с элементами нотации Диаграммы Эффектов.
++++

== Об авторе

Я занимаюсь коммерческой разработкой ПО с 2005 года и преподаю на ФИТ НГУ и ВКИ НГУ с 2007 года.

За это время я был разработчиком или техлидом/архитектором 30 проектов для различных отраслей - от встроенного ПО для приставок кабельного телевидения и систем промышленного видеонаблюдения до АИИС КУЭ для ПАО "Транснефть" и проекта по анализу больших данных.

Моя практика за эти годы показала, что процесс проектирования в нашей индустрии всё ещё не стал инженерной деятельностью, а скорее представляет собой смесь искусства и ремесла.
Следствием этого, зачастую, становится чрезмерная стоимость проекта, обусловленная серьёзными ошибками в дизайне.

Для того чтобы сделать проектирование более стандартизированным и предсказуемым я разработал Диаграмму Эффектов.
Процесс декомпозиции системы на базе Диаграммы Эффектов является основой и отличительной чертой "Эргономичного подхода" - моего метода создания програм с минимальной итоговой стоимостью.

Если у вас появились вопросы по Диаграмме Эффектов - буду рад ответить на них:

. Email: me@azhidkov.pro
. Telegram: d-r-q
